let def_tests_project = Array(
    // id_project
    Array('project','id_project',1,'cumple tamaño maximo','SEARCH','id_project_size_max_KO','Tamaño muy grande. El ID no puede tener más de 11 caracteres'),
    Array('project','id_project',2,'cumple formato','SEARCH','id_project_format_KO','Formato invalido. El ID contiene caracteres no permitidos (solo dígitos)'),
    Array('project','id_project',3,'es correcto','SEARCH',true,'ID correcto'),
    // name_project
    Array('project','name_project',4,'cumple tamaño minimo','ADD','name_project_min_size_KO','Tamaño demasiado corto. Debe tener al menos 15 caracteres'),
    Array('project','name_project',5,'cumple tamaño maximo','ADD','name_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 100 caracteres'),
    Array('project','name_project',6,'cumple formato','ADD','name_project_format_KO','Formato invalido. Solo se permiten caracteres alfabeticos y espacios, sin acentos ni ñ'),
    Array('project','name_project',7,'es correcto','ADD',true,'Nombre correcto'),
    Array('project','name_project',8,'cumple tamaño minimo','EDIT','name_project_min_size_KO','Tamaño demasiado corto. Debe tener al menos 15 caracteres'),
    Array('project','name_project',9,'cumple tamaño maximo','EDIT','name_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 100 caracteres'),
    Array('project','name_project',10,'cumple formato','EDIT','name_project_format_KO','Formato invalido. Solo se permiten caracteres alfabeticos y espacios, sin acentos ni ñ'),
    Array('project','name_project',11,'es correcto','EDIT',true,'Nombre correcto'),
    Array('project','name_project',12,'cumple tamaño maximo','SEARCH','name_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 100 caracteres'),
    Array('project','name_project',13,'cumple formato','SEARCH','name_project_format_KO','Formato invalido. Solo se permiten caracteres alfabeticos y espacios, sin acentos ni ñ'),
    Array('project','name_project',14,'es correcto','SEARCH',true,'Nombre correcto'),
    // start_date_project
    Array('project','start_date_project',15,'cumple formato','ADD','start_date_project_format_KO','Formato invalido. Solo se permite formato dd/mm/aaaa'),
    Array('project','start_date_project',16,'fecha valida','ADD','start_date_project_valid_KO','Fecha invalida'),
    Array('project','start_date_project',17,'es correcto','ADD',true,'Fecha correcta'),
    Array('project','start_date_project',18,'cumple formato','EDIT','start_date_project_format_KO','Formato invalido. Solo se permite formato dd/mm/aaaa'),
    Array('project','start_date_project',19,'fecha valida','EDIT','start_date_project_valid_KO','Fecha invalida'),
    Array('project','start_date_project',20,'es correcto','EDIT',true,'Fecha correcta'),
    Array('project','start_date_project',21,'cumple formato','SEARCH','start_date_project_format_KO','Formato invalido. Solo se permite formato dd/mm/aaaa'),
    Array('project','start_date_project',22,'es correcto','SEARCH',true,'Fecha correcta'),
    // end_date_project
    Array('project','end_date_project',23,'cumple formato','ADD','end_date_project_format_KO','Formato invalido. Solo se permite formato dd/mm/aaaa'),
    Array('project','end_date_project',24,'fecha valida','ADD','end_date_project_valid_KO','Fecha invalida'),
    Array('project','end_date_project',25,'es correcto','ADD',true,'Fecha correcta'),
    Array('project','end_date_project',26,'cumple formato','EDIT','end_date_project_format_KO','Formato invalido. Solo se permite formato dd/mm/aaaa'),
    Array('project','end_date_project',27,'fecha valida','EDIT','end_date_project_valid_KO','Fecha invalida'),
    Array('project','end_date_project',28,'es correcto','EDIT',true,'Fecha correcta'),
    Array('project','end_date_project',29,'cumple formato','SEARCH','end_date_project_format_KO','Formato invalido. Solo se permite formato dd/mm/aaaa'),
    Array('project','end_date_project',30,'es correcto','SEARCH',true,'Fecha correcta'),
    // responsable_project
    Array('project','responsable_project',31,'cumple tamaño minimo','ADD','responsable_project_min_size_KO','Tamaño demasiado corto. Debe tener al menos 6 caracteres'),
    Array('project','responsable_project',32,'cumple tamaño maximo','ADD','responsable_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 60 caracteres'),
    Array('project','responsable_project',33,'cumple formato','ADD','responsable_project_format_KO','Formato invalido. Solo se permiten caracteres alfabeticos con espacios, con acentos o con ñ'),
    Array('project','responsable_project',34,'es correcto','ADD',true,'Responsable correcto'),
    Array('project','responsable_project',35,'cumple tamaño minimo','EDIT','responsable_project_min_size_KO','Tamaño demasiado corto. Debe tener al menos 6 caracteres'),
    Array('project','responsable_project',36,'cumple tamaño maximo','EDIT','responsable_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 60 caracteres'),
    Array('project','responsable_project',37,'cumple formato','EDIT','responsable_project_format_KO','Formato invalido. Solo se permiten caracteres alfabeticos con espacios, con acentos o con ñ'),
    Array('project','responsable_project',38,'es correcto','EDIT',true,'Responsable correcto'),
    Array('project','responsable_project',39,'cumple tamaño maximo','SEARCH','responsable_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 60 caracteres'),
    Array('project','responsable_project',40,'cumple formato','SEARCH','responsable_project_format_KO','Formato invalido. Solo se permiten caracteres alfabeticos con espacios, con acentos o con ñ'),
    Array('project','responsable_project',41,'es correcto','SEARCH',true,'Responsable correcto'),
    // organization_project
    Array('project','organization_project',42,'cumple tamaño minimo','ADD','organization_project_min_size_KO','Tamaño demasiado corto. Debe tener al menos 6 caracteres'),
    Array('project','organization_project',43,'cumple tamaño maximo','ADD','organization_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 100 caracteres'),
    Array('project','organization_project',44,'cumple formato','ADD','organization_project_format_KO','Formato invalido. Solo se permiten caracteres alfabeticos con espacios, con acentos o con ñ'),
    Array('project','organization_project',45,'es correcto','ADD',true,'Organizacion correcta'),
    Array('project','organization_project',46,'cumple tamaño minimo','EDIT','organization_project_min_size_KO','Tamaño demasiado corto. Debe tener al menos 6 caracteres'),
    Array('project','organization_project',47,'cumple tamaño maximo','EDIT','organization_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 100 caracteres'),
    Array('project','organization_project',48,'cumple formato','EDIT','organization_project_format_KO','Formato invalido. Solo se permiten caracteres alfabeticos con espacios, con acentos o con ñ'),
    Array('project','organization_project',49,'es correcto','EDIT',true,'Organizacion correcta'),
    Array('project','organization_project',50,'cumple tamaño maximo','SEARCH','organization_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 100 caracteres'),
    Array('project','organization_project',51,'cumple formato','SEARCH','organization_project_format_KO','Formato invalido. Solo se permiten caracteres alfabeticos con espacios, con acentos o con ñ'),
    Array('project','organization_project',52,'es correcto','SEARCH',true,'Organización correcta'),
    // description_project
    Array('project','description_project',53,'cumple tamaño minimo','ADD','description_project_min_size_KO','Tamaño demasiado corto. Debe tener al menos 30 caracteres'),
    Array('project','description_project',54,'cumple tamaño maximo','ADD','description_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 500 caracteres'),
    Array('project','description_project',55,'es correcto','ADD',true,'Descripcion correcta'),
    Array('project','description_project',56,'cumple tamaño minimo','EDIT','description_project_min_size_KO','Tamaño demasiado corto. Debe tener al menos 30 caracteres'),
    Array('project','description_project',57,'cumple tamaño maximo','EDIT','description_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 500 caracteres'),
    Array('project','description_project',58,'es correcto','EDIT',true,'Descripcion correcta'),
    Array('project','description_project',59,'cumple tamaño maximo','SEARCH','description_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 500 caracteres'),
    Array('project','description_project',60,'es correcto','SEARCH',true,'Descripcion correcta'),
    // code_project
    Array('project','code_project',61,'cumple tamaño minimo','ADD','code_project_min_size_KO','Tamaño demasiado corto. Debe tener al menos 6 caracteres'),
    Array('project','code_project',62,'cumple tamaño maximo','ADD','code_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 50 caracteres'),
    Array('project','code_project',63,'cumple formato','ADD','code_project_format_KO','Formato invalido. Se permiten alfabeticos con ñ, espacios y signos de puntuacion, pero no acentos'),
    Array('project','code_project',64,'es correcto','ADD',true,'Codigo correcto'),
    Array('project','code_project',65,'cumple tamaño minimo','EDIT','code_project_min_size_KO','Tamaño demasiado corto. Debe tener al menos 6 caracteres'),
    Array('project','code_project',66,'cumple tamaño maximo','EDIT','code_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 50 caracteres'),
    Array('project','code_project',67,'cumple formato','EDIT','code_project_format_KO','Formato invalido. Se permiten alfabeticos con ñ, espacios y signos de puntuacion, pero no acentos'),
    Array('project','code_project',68,'es correcto','EDIT',true,'Codigo correcto'),
    Array('project','code_project',69,'cumple tamaño maximo','SEARCH','code_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 50 caracteres'),
    Array('project','code_project',70,'cumple formato','SEARCH','code_project_format_KO','Formato invalido. Se permiten alfabeticos con ñ, espacios y signos de puntuacion, pero no acentos'),
    Array('project','code_project',71,'es correcto','SEARCH',true,'Codigo correcto'),
    // acronym_project
    Array('project','acronym_project',72,'cumple tamaño minimo','ADD','acronym_project_min_size_KO','Tamaño demasiado corto. Debe tener al menos 6 caracteres'),
    Array('project','acronym_project',73,'cumple tamaño maximo','ADD','acronym_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 15 caracteres'),
    Array('project','acronym_project',74,'cumple formato','ADD','acronym_project_format_KO','Formato invalido. Solo se permiten alfabeticos con ñ, espacios y signos de puntuacion'),
    Array('project','acronym_project',75,'es correcto','ADD',true,'Acronimo correcto'),
    Array('project','acronym_project',76,'cumple tamaño minimo','EDIT','acronym_project_min_size_KO','Tamaño demasiado corto. Debe tener al menos 6 caracteres'),
    Array('project','acronym_project',77,'cumple tamaño maximo','EDIT','acronym_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 15 caracteres'),
    Array('project','acronym_project',78,'cumple formato','EDIT','acronym_project_format_KO','Formato invalido. Solo se permiten alfabeticos con ñ, espacios y signos de puntuacion'),
    Array('project','acronym_project',79,'es correcto','EDIT',true,'Acronimo correcto'),
    Array('project','acronym_project',80,'cumple tamaño maximo','SEARCH','acronym_project_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 15 caracteres'),
    Array('project','acronym_project',81,'cumple formato','SEARCH','acronym_project_format_KO','Formato invalido. Solo se permiten alfabeticos con ñ, espacios y signos de puntuacion'),
    Array('project','acronym_project',82,'es correcto','SEARCH',true,'Acronimo correcto'),
    // id_sampling_methodology_project
    Array('project','id_sampling_methodology',83,'cumple tamaño minimo','ADD','id_sampling_methodology_min_size_KO','Tamaño demasiado corto. Debe tener al menos 1 caracter'),
    Array('project','id_sampling_methodology',84,'cumple tamaño maximo','ADD','id_sampling_methodology_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 11 caracteres'),
    Array('project','id_sampling_methodology',85,'cumple formato','ADD','id_sampling_methodology_format_KO','Formato invalido. Solo se permiten digitos'),
    Array('project','id_sampling_methodology',86,'es correcto','ADD',true,'ID de metodologia de muestreo correcto'),
    Array('project','id_sampling_methodology',87,'cumple tamaño minimo','EDIT','id_sampling_methodology_min_size_KO','Tamaño demasiado corto. Debe tener al menos 1 caracter'),
    Array('project','id_sampling_methodology',88,'cumple tamaño maximo','EDIT','id_sampling_methodology_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 11 caracteres'),
    Array('project','id_sampling_methodology',89,'cumple formato','EDIT','id_sampling_methodology_format_KO','Formato invalido. Solo se permiten digitos'),
    Array('project','id_sampling_methodology',90,'es correcto','EDIT',true,'ID de metodologia de muestreo correcto'),
    Array('project','id_sampling_methodology',91,'cumple tamaño maximo','SEARCH','id_sampling_methodology_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 11 caracteres'),
    Array('project','id_sampling_methodology',92,'cumple formato','SEARCH','id_sampling_methodology_format_KO','Formato invalido. Solo se permiten digitos'),
    Array('project','id_sampling_methodology',93,'es correcto','SEARCH',true,'ID de metodologia de muestreo correcto'),
    // file_project
    Array('project','file_project',94,'cumple nombre fichero','SEARCH','file_project_format_name_file_KO','El nombre del fichero no cumple el formato'),
    Array('project','file_project',95,'cumple tamaño máximo nombre fichero','SEARCH','file_project_max_size_name_KO','El tamaño del nombre del fichero es muy grande. Debe tener como máximo 100 caracteres'),
    Array('project','file_project',96,'fichero ok','SEARCH',true,'OK.'),
    Array('project','nuevo_file_project',97,'existe fichero','ADD','nuevo_file_project_empty_KO','El fichero no existe. Debe subir un archivo'),
    Array('project','nuevo_file_project',98,'cumple nombre fichero','ADD','nuevo_file_project_format_name_file_KO','El nombre del fichero no cumple el formato'),
    Array('project','nuevo_file_project',99,'cumple tipo fichero','ADD','nuevo_file_project_type_file_KO','El tipo de fichero no está permitido. Solo se aceptan .pdf, .doc o .docx'),
    Array('project','nuevo_file_project',100,'cumple tamaño máximo fichero','ADD','nuevo_file_project_max_size_file_KO','El tamaño del fichero es muy grande. No debe superar los 2 MB'),
    Array('project','nuevo_file_project',101,'cumple tamaño mínimo nombre fichero','ADD','nuevo_file_project_min_size_name_KO','El tamaño del nombre del fichero es muy pequeño. Debe tener al menos 7 caracteres'),
    Array('project','nuevo_file_project',102,'cumple tamaño máximo nombre fichero','ADD','nuevo_file_project_max_size_name_KO','El tamaño del nombre del fichero es muy grande. Debe tener como máximo 100 caracteres'),
    Array('project','nuevo_file_project',103,'fichero ok','ADD', true, 'Fichero correcto'),
    Array('project','nuevo_file_project',104,'no existe fichero','EDIT', true,'OK.'),
    Array('project','nuevo_file_project',105,'cumple nombre fichero','EDIT','nuevo_file_project_format_name_file_KO','El nombre del fichero no cumple el formato'),
    Array('project','nuevo_file_project',106,'cumple tipo fichero','EDIT','nuevo_file_project_type_file_KO','El tipo de fichero no está permitido. Solo se aceptan .pdf, .doc o .docx'),
    Array('project','nuevo_file_project',107,'cumple tamaño máximo fichero','EDIT','nuevo_file_project_max_size_file_KO','El tamaño del fichero es muy grande. No debe superar los 2 MB'),
    Array('project','nuevo_file_project',108,'cumple tamaño mínimo nombre fichero','EDIT','nuevo_file_project_min_size_name_KO','El tamaño del nombre del fichero es muy pequeño. Debe tener al menos 7 caracteres'),
    Array('project','nuevo_file_project',109,'cumple tamaño máximo nombre fichero','EDIT','nuevo_file_project_max_size_name_KO','El tamaño del nombre del fichero es muy grande. Debe tener como máximo 100 caracteres'),
    Array('project','nuevo_file_project',110,'fichero ok','EDIT',true,'OK.'),
);

let pruebas_project = Array(
    // Pruebas del campo id_project (SEARCH)
    Array('project','id_project',1,1,'SEARCH','1'.repeat(12),'id_project_max_size_KO'),
    Array('project','id_project',1,2,'SEARCH','123456789012','id_project_max_size_KO'),
    Array('project','id_project',1,3,'SEARCH','1'.repeat(13),'id_project_max_size_KO'),
    Array('project','id_project',1,4,'SEARCH','1'.repeat(15),'id_project_max_size_KO'),
    Array('project','id_project',1,5,'SEARCH','1'.repeat(20),'id_project_max_size_KO'),
    Array('project','id_project',1,6,'SEARCH','1'.repeat(50),'id_project_max_size_KO'),
    Array('project','id_project',1,7,'SEARCH','1'.repeat(100),'id_project_max_size_KO'),
    Array('project','id_project',2,8,'SEARCH','abcdef','id_project_format_KO'),
    Array('project','id_project',2,9,'SEARCH','1 1 1 1','id_project_format_KO'),
    Array('project','id_project',2,10,'SEARCH','áéíóú','id_project_format_KO'),
    Array('project','id_project',2,11,'SEARCH','ÁÉÍÓÚ','id_project_format_KO'),
    Array('project','id_project',2,12,'SEARCH','1ñ7','id_project_format_KO'),
    Array('project','id_project',2,13,'SEARCH','1.2.3.4.5','id_project_format_KO'),
    Array('project','id_project',2,14,'SEARCH','ññññññ','id_project_format_KO'),
    Array('project','id_project',2,15,'SEARCH','1.ñá7','id_project_format_KO'),
    Array('project','id_project',2,16,'SEARCH','a b c d e','id_project_format_KO'),
    Array('project','id_project',2,17,'SEARCH','123456!','id_project_format_KO'),
    Array('project','id_project',3,18,'SEARCH','123456',true),
    Array('project','id_project',3,19,'SEARCH','1',true),
    Array('project','id_project',3,20,'SEARCH','111111',true),
    Array('project','id_project',3,21,'SEARCH','1'.repeat(11),true),
    Array('project','id_project',3,22,'SEARCH','12345678901',true),

    // Pruebas del campo name_project (ADD)
    Array('project','name_project',4,23,'ADD','a'.repeat(14),'name_project_min_size_KO'),
    Array('project','name_project',4,24,'ADD','a'.repeat(13),'name_project_min_size_KO'),
    Array('project','name_project',4,25,'ADD','a'.repeat(12),'name_project_min_size_KO'),
    Array('project','name_project',4,26,'ADD','a'.repeat(11),'name_project_min_size_KO'),
    Array('project','name_project',4,27,'ADD','a'.repeat(10),'name_project_min_size_KO'),
    Array('project','name_project',4,28,'ADD','a'.repeat(9),'name_project_min_size_KO'),
    Array('project','name_project',4,29,'ADD','a'.repeat(8),'name_project_min_size_KO'),
    Array('project','name_project',4,30,'ADD','a'.repeat(7),'name_project_min_size_KO'),
    Array('project','name_project',4,31,'ADD','a'.repeat(6),'name_project_min_size_KO'),
    Array('project','name_project',4,32,'ADD','nombre','name_project_min_size_KO'),
    Array('project','name_project',5,33,'ADD','a'.repeat(101),'name_project_max_size_KO'),
    Array('project','name_project',5,34,'ADD','a'.repeat(102),'name_project_max_size_KO'),
    Array('project','name_project',5,35,'ADD','a'.repeat(103),'name_project_max_size_KO'),
    Array('project','name_project',5,36,'ADD','a'.repeat(104),'name_project_max_size_KO'),
    Array('project','name_project',5,37,'ADD','a'.repeat(105),'name_project_max_size_KO'),
    Array('project','name_project',6,38,'ADD','á'.repeat(15),'name_project_format_KO'),
    Array('project','name_project',6,39,'ADD','PróyéctoÓÓOOOOOO1','name_project_format_KO'),
    Array('project','name_project',6,40,'ADD','pro.yec.to.o.o.o.o.o','name_project_format_KO'),
    Array('project','name_project',6,41,'ADD','proyecto-11111111111','name_project_format_KO'),
    Array('project','name_project',6,42,'ADD','análisis entrega con acento','name_project_format_KO'),
    Array('project','name_project',6,43,'ADD','Prueba Próyécto Con Ñ','name_project_format_KO'),
    Array('project','name_project',6,44,'ADD','Prueba Proyecto Con Ñ','name_project_format_KO'),
    Array('project','name_project',7,45,'ADD','Prueba Proyecto Nombre',true),
    Array('project','name_project',7,46,'ADD','prueba proyecto nombre',true),
    Array('project','name_project',7,47,'ADD','PROYECTO NOMBRE CORRECTO',true),
    Array('project','name_project',7,48,'ADD','proyecto nombre correcto',true),
    // Pruebas del campo name_project (EDIT)
    Array('project','name_project',8,49,'EDIT','a'.repeat(14),'name_project_min_size_KO'),
    Array('project','name_project',8,50,'EDIT','a'.repeat(13),'name_project_min_size_KO'),
    Array('project','name_project',8,51,'EDIT','a'.repeat(12),'name_project_min_size_KO'),
    Array('project','name_project',8,52,'EDIT','a'.repeat(11),'name_project_min_size_KO'),
    Array('project','name_project',8,53,'EDIT','a'.repeat(10),'name_project_min_size_KO'),
    Array('project','name_project',8,54,'EDIT','a'.repeat(9),'name_project_min_size_KO'),
    Array('project','name_project',8,55,'EDIT','a'.repeat(8),'name_project_min_size_KO'),
    Array('project','name_project',8,56,'EDIT','a'.repeat(7),'name_project_min_size_KO'),
    Array('project','name_project',8,57,'EDIT','a'.repeat(6),'name_project_min_size_KO'),
    Array('project','name_project',8,58,'EDIT','nombre','name_project_min_size_KO'),
    Array('project','name_project',9,59,'EDIT','a'.repeat(101),'name_project_max_size_KO'),
    Array('project','name_project',9,60,'EDIT','a'.repeat(102),'name_project_max_size_KO'),
    Array('project','name_project',9,61,'EDIT','a'.repeat(103),'name_project_max_size_KO'),
    Array('project','name_project',9,62,'EDIT','a'.repeat(104),'name_project_max_size_KO'),
    Array('project','name_project',9,63,'EDIT','a'.repeat(105),'name_project_max_size_KO'),
    Array('project','name_project',10,64,'EDIT','á'.repeat(15),'name_project_format_KO'),
    Array('project','name_project',10,65,'EDIT','PróyéctoÓÓOOOOOO1','name_project_format_KO'),
    Array('project','name_project',10,66,'EDIT','pro.yec.to.o.o.o.o.o','name_project_format_KO'),
    Array('project','name_project',10,67,'EDIT','proyecto-1111111111','name_project_format_KO'),
    Array('project','name_project',10,68,'EDIT','análisis entrega con acento','name_project_format_KO'),
    Array('project','name_project',10,69,'EDIT','Prueba Próyécto Con Ñ','name_project_format_KO'),
    Array('project','name_project',10,70,'EDIT','Prueba Proyecto Con Ñ','name_project_format_KO'),
    Array('project','name_project',11,71,'EDIT','Prueba Proyecto Nombre',true),
    Array('project','name_project',11,72,'EDIT','prueba proyecto nombre',true),
    Array('project','name_project',11,73,'EDIT','PROYECTO NOMBRE CORRECTO',true),
    Array('project','name_project',11,74,'EDIT','proyecto nombre correcto',true),
    // Pruebas del campo name_project (SEARCH)
    Array('project','name_project',12,75,'SEARCH','a'.repeat(101),'name_project_max_size_KO'),
    Array('project','name_project',12,76,'SEARCH','a'.repeat(102),'name_project_max_size_KO'),
    Array('project','name_project',12,77,'SEARCH','a'.repeat(103),'name_project_max_size_KO'),
    Array('project','name_project',12,78,'SEARCH','a'.repeat(104),'name_project_max_size_KO'),
    Array('project','name_project',12,79,'SEARCH','a'.repeat(105),'name_project_max_size_KO'),
    Array('project','name_project',13,80,'SEARCH','á'.repeat(15),'name_project_format_KO'),
    Array('project','name_project',13,81,'SEARCH','PróyéctoÓÓOOOOOO1','name_project_format_KO'),
    Array('project','name_project',13,82,'SEARCH','pro.yec.to.o.o.o.o.o','name_project_format_KO'),
    Array('project','name_project',13,83,'SEARCH','proyecto-1111111111','name_project_format_KO'),
    Array('project','name_project',13,84,'SEARCH','análisis entrega con acento','name_project_format_KO'),
    Array('project','name_project',13,85,'SEARCH','Prueba Próyécto Con Ñ','name_project_format_KO'),
    Array('project','name_project',13,86,'SEARCH','Prueba Proyecto Con Ñ','name_project_format_KO'),
    Array('project','name_project',14,87,'SEARCH','Prueba Proyecto Nombre',true),
    Array('project','name_project',14,88,'SEARCH','PROYECTO NOMBRE CORRECTO',true),
    Array('project','name_project',14,89,'SEARCH','proyecto nombre correcto',true),

    // Pruebas del campo start_date_project (ADD)
    Array('project','start_date_project',15,90,'ADD','30.01.2024','start_date_project_format_KO'), 
    Array('project','start_date_project',15,91,'ADD','31-12-2024','start_date_project_format_KO'), 
    Array('project','start_date_project',15,92,'ADD','2024/12/31','start_date_project_format_KO'), 
    Array('project','start_date_project',15,93,'ADD','1/1/202','start_date_project_format_KO'),
    Array('project','start_date_project',16,94,'ADD','34/02/2023','start_date_project_valid_KO'), 
    Array('project','start_date_project',16,95,'ADD','00/12/2024','start_date_project_valid_KO'), 
    Array('project','start_date_project',16,96,'ADD','99/99/2024','start_date_project_valid_KO'), 
    Array('project','start_date_project',17,97,'ADD','01/01/1999',true), 
    Array('project','start_date_project',17,98,'ADD','29/02/2024',true), 
    Array('project','start_date_project',17,99,'ADD','31/12/2099',true), 
    // Pruebas del campo start_date_project (EDIT)
    Array('project','start_date_project',18,100,'EDIT','30.01.2024','start_date_project_format_KO'), 
    Array('project','start_date_project',18,101,'EDIT','31-12-2024','start_date_project_format_KO'), 
    Array('project','start_date_project',18,102,'EDIT','2024/12/31','start_date_project_format_KO'), 
    Array('project','start_date_project',18,103,'EDIT','1/1/202','start_date_project_format_KO'), 
    Array('project','start_date_project',19,104,'EDIT','34/02/2023','start_date_project_valid_KO'), 
    Array('project','start_date_project',19,105,'EDIT','00/12/2024','start_date_project_valid_KO'), 
    Array('project','start_date_project',19,106,'EDIT','99/99/2024','start_date_project_valid_KO'), 
    Array('project','start_date_project',20,107,'EDIT','01/01/1999',true), 
    Array('project','start_date_project',20,108,'EDIT','29/02/2024',true), 
    Array('project','start_date_project',20,109,'EDIT','31/12/2099',true), 
    // Pruebas del campo start_date_project (SEARCH)
    Array('project','start_date_project',21,110,'SEARCH','30.01.2024','start_date_project_format_KO'), 
    Array('project','start_date_project',21,111,'SEARCH','31-12-2024','start_date_project_format_KO'), 
    Array('project','start_date_project',21,112,'SEARCH','2024/12/31','start_date_project_format_KO'), 
    Array('project','start_date_project',21,113,'SEARCH','1/1/202','start_date_project_format_KO'), 
    Array('project','start_date_project',22,114,'SEARCH','',true), 
    Array('project','start_date_project',22,115,'SEARCH','29/02/2024',true),
    Array('project','start_date_project',22,116,'SEARCH','31/12/2099',true),

    // Pruebas del campo end_date_project (ADD)
    Array('project','end_date_project',23,117,'ADD','30.01.2024','end_date_project_format_KO'), 
    Array('project','end_date_project',23,118,'ADD','31-12-2024','end_date_project_format_KO'), 
    Array('project','end_date_project',23,119,'ADD','2024/12/31','end_date_project_format_KO'), 
    Array('project','end_date_project',23,120,'ADD','1/1/202','end_date_project_format_KO'),
    Array('project','end_date_project',24,121,'ADD','34/02/2023','end_date_project_valid_KO'), 
    Array('project','end_date_project',24,122,'ADD','00/12/2024','end_date_project_valid_KO'), 
    Array('project','end_date_project',24,123,'ADD','99/99/2024','end_date_project_valid_KO'), 
    Array('project','end_date_project',25,124,'EDIT','01/01/1999',true), 
    Array('project','end_date_project',25,125,'EDIT','29/02/2024',true), 
    Array('project','end_date_project',25,126,'EDIT','31/12/2099',true), 
    // Pruebas del campo end_date_project (EDIT)
    Array('project','end_date_project',26,127,'EDIT','30.01.2024','end_date_project_format_KO'), 
    Array('project','end_date_project',26,128,'EDIT','31-12-2024','end_date_project_format_KO'), 
    Array('project','end_date_project',26,129,'EDIT','2024/12/31','end_date_project_format_KO'), 
    Array('project','end_date_project',26,130,'EDIT','1/1/202','end_date_project_format_KO'), 
    Array('project','end_date_project',27,131,'EDIT','34/02/2023','end_date_project_valid_KO'), 
    Array('project','end_date_project',27,132,'EDIT','00/12/2024','end_date_project_valid_KO'), 
    Array('project','end_date_project',27,133,'EDIT','99/99/2024','end_date_project_valid_KO'), 
    Array('project','end_date_project',28,134,'EDIT','01/01/1999',true), 
    Array('project','end_date_project',28,135,'EDIT','29/02/2024',true), 
    Array('project','end_date_project',28,136,'EDIT','31/12/2099',true), 
    // Pruebas del campo end_date_project (SEARCH)
    Array('project','end_date_project',29,137,'SEARCH','30.01.2024','end_date_project_format_KO'), 
    Array('project','end_date_project',29,138,'SEARCH','31-12-2024','end_date_project_format_KO'), 
    Array('project','end_date_project',29,139,'SEARCH','2024/12/31','end_date_project_format_KO'), 
    Array('project','end_date_project',29,140,'SEARCH','1/1/202','end_date_project_format_KO'), 
    Array('project','end_date_project',30,141,'SEARCH','',true), 
    Array('project','end_date_project',30,142,'SEARCH','29/02/2024',true),
    Array('project','end_date_project',30,143,'SEARCH','31/12/2099',true),

    // Pruebas del campo responsable_project (ADD)
    Array('project','responsable_project',31,144,'ADD','a'.repeat(5),'responsable_project_min_size_KO'),
    Array('project','responsable_project',31,145,'ADD','a'.repeat(4),'responsable_project_min_size_KO'),
    Array('project','responsable_project',31,146,'ADD','a'.repeat(3),'responsable_project_min_size_KO'),
    Array('project','responsable_project',31,147,'ADD','aa','responsable_project_min_size_KO'),
    Array('project','responsable_project',31,148,'ADD','a','responsable_project_min_size_KO'),
    Array('project','responsable_project',31,149,'ADD','resp','responsable_project_min_size_KO'),
    Array('project','responsable_project',32,150,'ADD','a'.repeat(61),'responsable_project_max_size_KO'),
    Array('project','responsable_project',32,151,'ADD','a'.repeat(62),'responsable_project_max_size_KO'),
    Array('project','responsable_project',32,152,'ADD','a'.repeat(63),'responsable_project_max_size_KO'),
    Array('project','responsable_project',32,153,'ADD','a'.repeat(64),'responsable_project_max_size_KO'),
    Array('project','responsable_project',32,154,'ADD','a'.repeat(65),'responsable_project_max_size_KO'),
    Array('project','responsable_project',33,155,'ADD','123HolaMundo','responsable_project_format_KO'),
    Array('project','responsable_project',33,156,'ADD','resp.onsab.le','responsable_project_format_KO'),
    Array('project','responsable_project',33,157,'ADD','responsable*','responsable_project_format_KO'),
    Array('project','responsable_project',33,158,'ADD','tu responsable,hola','responsable_project_format_KO'),
    Array('project','responsable_project',33,159,'ADD','responsable 1','responsable_project_format_KO'),
    Array('project','responsable_project',33,160,'ADD','1234567890','responsable_project_format_KO'),
    Array('project','responsable_project',33,161,'ADD','!!*..;,!?','responsable_project_format_KO'),
    Array('project','responsable_project',34,162,'ADD','Prueba Responsable Nombre',true),
    Array('project','responsable_project',34,163,'ADD','prueba responsable ñü nombre',true),
    Array('project','responsable_project',34,164,'ADD','RESPONSABLE NOMBRE CORRECTO',true),
    Array('project','responsable_project',34,165,'ADD','responsable nombre correcto',true),
    Array('project','responsable_project',34,166,'ADD','responsable',true),
    Array('project','responsable_project',34,167,'ADD','RESPONSABLE',true),
    // Pruebas del campo responsable_project (EDIT)
    Array('project','responsable_project',35,168,'EDIT','a'.repeat(5),'responsable_project_min_size_KO'),
    Array('project','responsable_project',35,169,'EDIT','a'.repeat(4),'responsable_project_min_size_KO'),
    Array('project','responsable_project',35,170,'EDIT','a'.repeat(3),'responsable_project_min_size_KO'),
    Array('project','responsable_project',35,171,'EDIT','aa','responsable_project_min_size_KO'),
    Array('project','responsable_project',35,172,'EDIT','a','responsable_project_min_size_KO'),
    Array('project','responsable_project',35,173,'EDIT','resp','responsable_project_min_size_KO'),
    Array('project','responsable_project',36,174,'EDIT','a'.repeat(61),'responsable_project_max_size_KO'),
    Array('project','responsable_project',36,175,'EDIT','a'.repeat(62),'responsable_project_max_size_KO'),
    Array('project','responsable_project',36,176,'EDIT','a'.repeat(63),'responsable_project_max_size_KO'),
    Array('project','responsable_project',36,177,'EDIT','a'.repeat(64),'responsable_project_max_size_KO'),
    Array('project','responsable_project',36,178,'EDIT','a'.repeat(65),'responsable_project_max_size_KO'),
    Array('project','responsable_project',37,179,'EDIT','123HolaMundo','responsable_project_format_KO'),
    Array('project','responsable_project',37,180,'EDIT','resp.onsab.le','responsable_project_format_KO'),
    Array('project','responsable_project',37,181,'EDIT','responsable*','responsable_project_format_KO'),
    Array('project','responsable_project',37,182,'EDIT','tu responsable,hola','responsable_project_format_KO'),
    Array('project','responsable_project',37,183,'EDIT','responsable 1','responsable_project_format_KO'),
    Array('project','responsable_project',37,184,'EDIT','1234567890','responsable_project_format_KO'),
    Array('project','responsable_project',37,185,'EDIT','!!*..;,!?','responsable_project_format_KO'),
    Array('project','responsable_project',38,186,'EDIT','Prueba Responsable Nombre',true),
    Array('project','responsable_project',38,187,'EDIT','prueba responsable ñü nombre',true),
    Array('project','responsable_project',38,188,'EDIT','RESPONSABLE NOMBRE CORRECTO',true),
    Array('project','responsable_project',38,189,'EDIT','responsable nombre correcto',true),
    Array('project','responsable_project',38,190,'EDIT','responsable',true),
    Array('project','responsable_project',38,191,'EDIT','RESPONSABLE',true),
    // Pruebas del campo responsable_project (SEARCH)
    Array('project','responsable_project',39,192,'SEARCH','a'.repeat(61),'responsable_project_max_size_KO'),
    Array('project','responsable_project',39,193,'SEARCH','a'.repeat(62),'responsable_project_max_size_KO'),
    Array('project','responsable_project',39,194,'SEARCH','a'.repeat(63),'responsable_project_max_size_KO'),
    Array('project','responsable_project',39,195,'SEARCH','a'.repeat(64),'responsable_project_max_size_KO'),
    Array('project','responsable_project',39,196,'SEARCH','a'.repeat(65),'responsable_project_max_size_KO'),
    Array('project','responsable_project',40,197,'SEARCH','123HolaMundo','responsable_project_format_KO'),
    Array('project','responsable_project',40,198,'SEARCH','resp.onsab.le','responsable_project_format_KO'),
    Array('project','responsable_project',40,199,'SEARCH','responsable*','responsable_project_format_KO'),
    Array('project','responsable_project',40,200,'SEARCH','tu responsable,hola','responsable_project_format_KO'),
    Array('project','responsable_project',40,201,'SEARCH','responsable 1','responsable_project_format_KO'),
    Array('project','responsable_project',40,202,'SEARCH','1234567890','responsable_project_format_KO'),
    Array('project','responsable_project',40,203,'SEARCH','!!*..;,!?','responsable_project_format_KO'),
    Array('project','responsable_project',41,204,'SEARCH','Prueba Responsable Nombre',true),
    Array('project','responsable_project',41,205,'SEARCH','prueba responsable ñü nombre',true),
    Array('project','responsable_project',41,206,'SEARCH','RESPONSABLE NOMBRE CORRECTO',true),
    Array('project','responsable_project',41,207,'SEARCH','responsable nombre correcto',true),
    Array('project','responsable_project',41,208,'SEARCH','responsable',true),
    Array('project','responsable_project',41,209,'SEARCH','RESPONSABLE',true),

    // Pruebas del campo organization_project (ADD)
    Array('project','organization_project',42,210,'ADD','a'.repeat(5),'organization_project_min_size_KO'),
    Array('project','organization_project',42,211,'ADD','a'.repeat(4),'organization_project_min_size_KO'),
    Array('project','organization_project',42,212,'ADD','a'.repeat(3),'organization_project_min_size_KO'),
    Array('project','organization_project',42,213,'ADD','aa','organization_project_min_size_KO'),
    Array('project','organization_project',42,214,'ADD','a','organization_project_min_size_KO'),
    Array('project','organization_project',42,215,'ADD','org','organization_project_min_size_KO'),
    Array('project','organization_project',43,216,'ADD','a'.repeat(101),'organization_project_max_size_KO'),
    Array('project','organization_project',43,217,'ADD','a'.repeat(102),'organization_project_max_size_KO'),
    Array('project','organization_project',43,218,'ADD','a'.repeat(103),'organization_project_max_size_KO'),
    Array('project','organization_project',43,219,'ADD','a'.repeat(104),'organization_project_max_size_KO'),
    Array('project','organization_project',43,220,'ADD','a'.repeat(105),'organization_project_max_size_KO'),
    Array('project','organization_project',44,221,'ADD','123HolaMundo','organization_project_format_KO'),
    Array('project','organization_project',44,222,'ADD','org.aniz.acion','organization_project_format_KO'),
    Array('project','organization_project',44,223,'ADD','organización*','organization_project_format_KO'),
    Array('project','organization_project',44,224,'ADD','tu organización,hola','organization_project_format_KO'),
    Array('project','organization_project',44,225,'ADD','organización 1','organization_project_format_KO'),
    Array('project','organization_project',44,226,'ADD','1234567890','organization_project_format_KO'),
    Array('project','organization_project',44,227,'ADD','!!*..;,!?','organization_project_format_KO'),
    Array('project','organization_project',45,228,'ADD','Prueba Organización Nombre',true),
    Array('project','organization_project',45,229,'ADD','prueba organización ñü nombre',true),
    Array('project','organization_project',45,230,'ADD','ORGANIZACION NOMBRE CORRECTO',true),
    Array('project','organization_project',45,231,'ADD','organización nombre correcto',true),
    Array('project','organization_project',45,232,'ADD','organización',true),
    Array('project','organization_project',45,233,'ADD','ORGANIZACION',true),
    // Pruebas del campo organization_project (EDIT)
    Array('project','organization_project',46,234,'EDIT','a'.repeat(5),'organization_project_min_size_KO'),
    Array('project','organization_project',46,235,'EDIT','a'.repeat(4),'organization_project_min_size_KO'),
    Array('project','organization_project',46,236,'EDIT','a'.repeat(3),'organization_project_min_size_KO'),
    Array('project','organization_project',46,237,'EDIT','aa','organization_project_min_size_KO'),
    Array('project','organization_project',46,238,'EDIT','a','organization_project_min_size_KO'),
    Array('project','organization_project',46,239,'EDIT','org','organization_project_min_size_KO'),
    Array('project','organization_project',47,240,'EDIT','a'.repeat(101),'organization_project_max_size_KO'),
    Array('project','organization_project',47,241,'EDIT','a'.repeat(102),'organization_project_max_size_KO'),
    Array('project','organization_project',47,242,'EDIT','a'.repeat(103),'organization_project_max_size_KO'),
    Array('project','organization_project',47,243,'EDIT','a'.repeat(104),'organization_project_max_size_KO'),
    Array('project','organization_project',47,244,'EDIT','a'.repeat(105),'organization_project_max_size_KO'),
    Array('project','organization_project',48,245,'EDIT','123HolaMundo','organization_project_format_KO'),
    Array('project','organization_project',48,246,'EDIT','org.aniz.acion','organization_project_format_KO'),
    Array('project','organization_project',48,247,'EDIT','organización*','organization_project_format_KO'),
    Array('project','organization_project',48,248,'EDIT','tu organización,hola','organization_project_format_KO'),
    Array('project','organization_project',48,249,'EDIT','organización 1','organization_project_format_KO'),
    Array('project','organization_project',48,250,'EDIT','1234567890','organization_project_format_KO'),
    Array('project','organization_project',48,251,'EDIT','!!*..;,!?','organization_project_format_KO'),
    Array('project','organization_project',49,252,'EDIT','Prueba Organización Nombre',true),
    Array('project','organization_project',49,253,'EDIT','prueba organización ñü nombre',true),
    Array('project','organization_project',49,254,'EDIT','ORGANIZACION NOMBRE CORRECTO',true),
    Array('project','organization_project',49,255,'EDIT','organización nombre correcto',true),
    Array('project','organization_project',49,256,'EDIT','organización',true),
    Array('project','organization_project',49,257,'EDIT','ORGANIZACION',true),
    // Pruebas del campo organization_project (SEARCH)
    Array('project','organization_project',50,258,'SEARCH','a'.repeat(101),'organization_project_max_size_KO'),
    Array('project','organization_project',50,259,'SEARCH','a'.repeat(102),'organization_project_max_size_KO'),
    Array('project','organization_project',50,260,'SEARCH','a'.repeat(103),'organization_project_max_size_KO'),
    Array('project','organization_project',50,261,'SEARCH','a'.repeat(104),'organization_project_max_size_KO'),
    Array('project','organization_project',50,262,'SEARCH','a'.repeat(105),'organization_project_max_size_KO'),
    Array('project','organization_project',51,263,'SEARCH','123HolaMundo','organization_project_format_KO'),
    Array('project','organization_project',51,264,'SEARCH','org.aniz.acion','organization_project_format_KO'),
    Array('project','organization_project',51,265,'SEARCH','organización*','organization_project_format_KO'),
    Array('project','organization_project',51,266,'SEARCH','tu organización,hola','organization_project_format_KO'),
    Array('project','organization_project',51,267,'SEARCH','organización 1','organization_project_format_KO'),
    Array('project','organization_project',51,268,'SEARCH','1234567890','organization_project_format_KO'),
    Array('project','organization_project',51,269,'SEARCH','!!*..;,!?','organization_project_format_KO'),
    Array('project','organization_project',52,270,'SEARCH','Prueba Organización Nombre',true),
    Array('project','organization_project',52,271,'SEARCH','prueba organización ñü nombre',true),
    Array('project','organization_project',52,272,'SEARCH','ORGANIZACION NOMBRE CORRECTO',true),
    Array('project','organization_project',52,273,'SEARCH','organización nombre correcto',true),
    Array('project','organization_project',52,274,'SEARCH','organización',true),
    Array('project','organization_project',52,275,'SEARCH','ORGANIZACION',true),

    //Pruebas del campo description_project (ADD)
    Array('project','description_project',53,276,'ADD','a'.repeat(29),'description_project_min_size_KO'),
    Array('project','description_project',53,277,'ADD','a'.repeat(28),'description_project_min_size_KO'),
    Array('project','description_project',53,278,'ADD','a'.repeat(27),'description_project_min_size_KO'),
    Array('project','description_project',53,279,'ADD','aa','description_project_min_size_KO'),
    Array('project','description_project',53,280,'ADD','a','description_project_min_size_KO'),
    Array('project','description_project',53,281,'ADD','descripcion','description_project_min_size_KO'),
    Array('project','description_project',54,282,'ADD','a'.repeat(501),'description_project_max_size_KO'),
    Array('project','description_project',54,283,'ADD','a'.repeat(502),'description_project_max_size_KO'),
    Array('project','description_project',54,284,'ADD','a'.repeat(503),'description_project_max_size_KO'),
    Array('project','description_project',54,285,'ADD','a'.repeat(504),'description_project_max_size_KO'),
    Array('project','description_project',54,286,'ADD','a'.repeat(505),'description_project_max_size_KO'),
    Array('project','description_project',55,287,'ADD','Esta es una descripción de 31 char',true),
    Array('project','description_project',55,288,'ADD','ESTA ES UNA DESCRIPCIÓN DE 31 CHAR',true),
    Array('project','description_project',55,289,'ADD','descripcion correcta!!!!!!!!!!!!!!',true),
    Array('project','description_project',55,290,'ADD','descripcion correcta11111111111111111',true),
    Array('project','description_project',55,291,'ADD','descripcion correcta. . . . . . . . . . . ',true),
    Array('project','description_project',55,292,'ADD','esta descripcion tambien me vale como correcta',true),
    // Pruebas del campo description_project (EDIT)
    Array('project','description_project',56,293,'EDIT','a'.repeat(29),'description_project_min_size_KO'),
    Array('project','description_project',56,294,'EDIT','a'.repeat(28),'description_project_min_size_KO'),
    Array('project','description_project',56,295,'EDIT','a'.repeat(27),'description_project_min_size_KO'),
    Array('project','description_project',56,296,'EDIT','aa','description_project_min_size_KO'),
    Array('project','description_project',56,297,'EDIT','a','description_project_min_size_KO'),
    Array('project','description_project',56,298,'EDIT','descripcion','description_project_min_size_KO'),
    Array('project','description_project',57,299,'EDIT','a'.repeat(501),'description_project_max_size_KO'),
    Array('project','description_project',57,300,'EDIT','a'.repeat(502),'description_project_max_size_KO'),
    Array('project','description_project',57,301,'EDIT','a'.repeat(503),'description_project_max_size_KO'),
    Array('project','description_project',57,302,'EDIT','a'.repeat(504),'description_project_max_size_KO'),
    Array('project','description_project',57,303,'EDIT','a'.repeat(505),'description_project_max_size_KO'),
    Array('project','description_project',57,304,'EDIT','a'.repeat(506),'description_project_max_size_KO'),
    Array('project','description_project',58,305,'EDIT','Esta es una descripción de 31 char',true),
    Array('project','description_project',58,306,'EDIT','ESTA ES UNA DESCRIPCIÓN DE 31 CHAR',true),
    Array('project','description_project',58,307,'EDIT','descripcion correcta!!!!!!!!!!!!!!',true),
    Array('project','description_project',58,308,'EDIT','descripcion correcta11111111111111111',true),
    Array('project','description_project',58,309,'EDIT','descripcion correcta. . . . . . . . . . . ',true),
    Array('project','description_project',58,310,'EDIT','esta descripcion tambien me vale como correcta',true),
    // Pruebas del campo description_project (SEARCH)
    Array('project','description_project',59,311,'SEARCH','a'.repeat(501),'description_project_max_size_KO'),
    Array('project','description_project',59,312,'SEARCH','a'.repeat(502),'description_project_max_size_KO'),
    Array('project','description_project',59,313,'SEARCH','a'.repeat(503),'description_project_max_size_KO'),
    Array('project','description_project',59,314,'SEARCH','a'.repeat(504),'description_project_max_size_KO'),
    Array('project','description_project',59,315,'SEARCH','a'.repeat(505),'description_project_max_size_KO'),
    Array('project','description_project',60,316,'SEARCH','Esta es una descripción de 31 char',true),
    Array('project','description_project',60,317,'SEARCH','ESTA ES UNA DESCRIPCIÓN DE 31 CHAR',true),
    Array('project','description_project',60,318,'SEARCH','descripcion correcta!!!!!!!!!!!!!!',true),
    Array('project','description_project',60,319,'SEARCH','descripcion correcta11111111111111111',true),
    Array('project','description_project',60,320,'SEARCH','descripcion correcta. . . . . . . . . . . ',true),
    Array('project','description_project',60,321,'SEARCH','esta descripcion tambien me vale como correcta',true),

    // Pruebas del campo code_project (ADD)
    Array('project','code_project',61,322,'ADD','a'.repeat(5),'code_project_min_size_KO'),
    Array('project','code_project',61,323,'ADD','a'.repeat(4),'code_project_min_size_KO'),
    Array('project','code_project',61,324,'ADD','a'.repeat(3),'code_project_min_size_KO'),
    Array('project','code_project',61,325,'ADD','aa','code_project_min_size_KO'),
    Array('project','code_project',61,326,'ADD','a','code_project_min_size_KO'),
    Array('project','code_project',61,327,'ADD','code','code_project_min_size_KO'),
    Array('project','code_project',62,328,'ADD','a'.repeat(51),'code_project_max_size_KO'),
    Array('project','code_project',62,329,'ADD','a'.repeat(52),'code_project_max_size_KO'),
    Array('project','code_project',62,330,'ADD','a'.repeat(53),'code_project_max_size_KO'),
    Array('project','code_project',62,331,'ADD','a'.repeat(54),'code_project_max_size_KO'),
    Array('project','code_project',62,332,'ADD','a'.repeat(55),'code_project_max_size_KO'),
    Array('project','code_project',63,333,'ADD','123HolaMundo','code_project_format_KO'),
    Array('project','code_project',63,334,'ADD','códigos','code_project_format_KO'),
    Array('project','code_project',63,335,'ADD','códigos.correctos','code_project_format_KO'),
    Array('project','code_project',63,336,'ADD','tu código','code_project_format_KO'),
    Array('project','code_project',63,337,'ADD','código 1','code_project_format_KO'),
    Array('project','code_project',63,338,'ADD','1234567890','code_project_format_KO'),
    Array('project','code_project',63,339,'ADD','código con ñ y acento','code_project_format_KO'),
    Array('project','code_project',64,340,'ADD','Prueba Codigo .,;:()[]-¡!¿?-"',true),
    Array('project','code_project',64,341,'ADD','prueba codigo',true),
    Array('project','code_project',64,342,'ADD','CODIGO CORRECTO',true),
    Array('project','code_project',64,343,'ADD','codigo correcto',true),
    Array('project','code_project',64,344,'ADD','codigo',true),
    Array('project','code_project',64,345,'ADD','CODIGO',true),
    // Pruebas del campo code_project (EDIT)
    Array('project','code_project',65,346,'EDIT','a'.repeat(5),'code_project_min_size_KO'),
    Array('project','code_project',65,347,'EDIT','a'.repeat(4),'code_project_min_size_KO'),
    Array('project','code_project',65,348,'EDIT','a'.repeat(3),'code_project_min_size_KO'),
    Array('project','code_project',65,349,'EDIT','aa','code_project_min_size_KO'),
    Array('project','code_project',65,350,'EDIT','a','code_project_min_size_KO'),
    Array('project','code_project',65,351,'EDIT','code','code_project_min_size_KO'),
    Array('project','code_project',66,352,'EDIT','a'.repeat(51),'code_project_max_size_KO'),
    Array('project','code_project',66,353,'EDIT','a'.repeat(52),'code_project_max_size_KO'),
    Array('project','code_project',66,354,'EDIT','a'.repeat(53),'code_project_max_size_KO'),
    Array('project','code_project',66,355,'EDIT','a'.repeat(54),'code_project_max_size_KO'),
    Array('project','code_project',66,356,'EDIT','a'.repeat(55),'code_project_max_size_KO'),
    Array('project','code_project',67,357,'EDIT','123HolaMundo','code_project_format_KO'),
    Array('project','code_project',67,358,'EDIT','códigos','code_project_format_KO'),
    Array('project','code_project',67,359,'EDIT','códigos.correctos','code_project_format_KO'),
    Array('project','code_project',67,360,'EDIT','tu código','code_project_format_KO'),
    Array('project','code_project',67,361,'EDIT','código 1','code_project_format_KO'),
    Array('project','code_project',67,362,'EDIT','1234567890','code_project_format_KO'),
    Array('project','code_project',67,363,'EDIT','código con ñ y acento','code_project_format_KO'),
    Array('project','code_project',68,364,'EDIT','Prueba Codigo .,;:()[]-¡!¿?-"',true),
    Array('project','code_project',68,365,'EDIT','prueba codigo',true),
    Array('project','code_project',68,366,'EDIT','CODIGO CORRECTO',true),
    Array('project','code_project',68,367,'EDIT','codigo correcto',true),
    Array('project','code_project',68,368,'EDIT','codigo',true),
    Array('project','code_project',68,369,'EDIT','CODIGO',true),
    // Pruebas del campo code_project (SEARCH)
    Array('project','code_project',69,370,'SEARCH','a'.repeat(51),'code_project_max_size_KO'),
    Array('project','code_project',69,371,'SEARCH','a'.repeat(52),'code_project_max_size_KO'),
    Array('project','code_project',69,372,'SEARCH','a'.repeat(53),'code_project_max_size_KO'),
    Array('project','code_project',69,373,'SEARCH','a'.repeat(54),'code_project_max_size_KO'),
    Array('project','code_project',69,374,'SEARCH','a'.repeat(55),'code_project_max_size_KO'),
    Array('project','code_project',70,375,'SEARCH','123HolaMundo','code_project_format_KO'),
    Array('project','code_project',70,376,'SEARCH','códigos','code_project_format_KO'),
    Array('project','code_project',70,377,'SEARCH','códigos.correctos','code_project_format_KO'),
    Array('project','code_project',70,378,'SEARCH','tu código','code_project_format_KO'),
    Array('project','code_project',70,379,'SEARCH','código 1','code_project_format_KO'),
    Array('project','code_project',70,380,'SEARCH','1234567890','code_project_format_KO'),
    Array('project','code_project',70,381,'SEARCH','código con ñ y acento','code_project_format_KO'),
    Array('project','code_project',71,382,'SEARCH','Prueba Codigo .,;:()[]-¡!¿?-"',true),
    Array('project','code_project',71,383,'SEARCH','prueba codigo',true),
    Array('project','code_project',71,384,'SEARCH','CODIGO CORRECTO',true),
    Array('project','code_project',71,385,'SEARCH','codigo correcto',true),
    Array('project','code_project',71,386,'SEARCH','codigo',true),
    Array('project','code_project',71,387,'SEARCH','CODIGO',true),

    // Pruebas del campo acronym_project (ADD)
    Array('project','acronym_project',72,388,'ADD','a'.repeat(5),'acronym_project_min_size_KO'),
    Array('project','acronym_project',72,389,'ADD','a'.repeat(4),'acronym_project_min_size_KO'),
    Array('project','acronym_project',72,390,'ADD','a'.repeat(3),'acronym_project_min_size_KO'),
    Array('project','acronym_project',72,391,'ADD','aa','acronym_project_min_size_KO'),
    Array('project','acronym_project',72,392,'ADD','a','acronym_project_min_size_KO'),
    Array('project','acronym_project',72,393,'ADD','acr','acronym_project_min_size_KO'),
    Array('project','acronym_project',73,394,'ADD','a'.repeat(16),'acronym_project_max_size_KO'),
    Array('project','acronym_project',73,395,'ADD','a'.repeat(17),'acronym_project_max_size_KO'),
    Array('project','acronym_project',73,396,'ADD','a'.repeat(18),'acronym_project_max_size_KO'),
    Array('project','acronym_project',73,397,'ADD','a'.repeat(19),'acronym_project_max_size_KO'),
    Array('project','acronym_project',73,398,'ADD','a'.repeat(20),'acronym_project_max_size_KO'),
    Array('project','acronym_project',74,399,'ADD','123Acronym','acronym_project_format_KO'),
    Array('project','acronym_project',74,400,'ADD','acrónimos','acronym_project_format_KO'),
    Array('project','acronym_project',74,401,'ADD','acrónimos.c','acronym_project_format_KO'),
    Array('project','acronym_project',74,402,'ADD','tu acronimo','acronym_project_format_KO'),
    Array('project','acronym_project',74,403,'ADD','acrónimo 1','acronym_project_format_KO'),
    Array('project','acronym_project',74,404,'ADD','1234567890','acronym_project_format_KO'),
    Array('project','acronym_project',74,405,'ADD','acrónimo con ñ','acronym_project_format_KO'),
    Array('project','acronym_project',75,406,'ADD','.,;:()[]-¡!¿?-"',true),
    Array('project','acronym_project',75,407,'ADD','acronimo',true),
    Array('project','acronym_project',75,408,'ADD','ACRONIMO',true),
    Array('project','acronym_project',75,409,'ADD','acronimo.',true),
    Array('project','acronym_project',75,410,'ADD','acroñimo',true),
    Array('project','acronym_project',75,411,'ADD','ACRONIMO!',true),
    // Pruebas del campo acronym_project (EDIT)
    Array('project','acronym_project',76,412,'EDIT','a'.repeat(5),'acronym_project_min_size_KO'),
    Array('project','acronym_project',76,413,'EDIT','a'.repeat(4),'acronym_project_min_size_KO'),
    Array('project','acronym_project',76,414,'EDIT','a'.repeat(3),'acronym_project_min_size_KO'),
    Array('project','acronym_project',76,415,'EDIT','aa','acronym_project_min_size_KO'),
    Array('project','acronym_project',76,416,'EDIT','a','acronym_project_min_size_KO'),
    Array('project','acronym_project',76,417,'EDIT','acr','acronym_project_min_size_KO'),
    Array('project','acronym_project',77,418,'EDIT','a'.repeat(16),'acronym_project_max_size_KO'),
    Array('project','acronym_project',77,419,'EDIT','a'.repeat(17),'acronym_project_max_size_KO'),
    Array('project','acronym_project',77,420,'EDIT','a'.repeat(18),'acronym_project_max_size_KO'),
    Array('project','acronym_project',77,421,'EDIT','a'.repeat(19),'acronym_project_max_size_KO'),
    Array('project','acronym_project',77,422,'EDIT','a'.repeat(20),'acronym_project_max_size_KO'),
    Array('project','acronym_project',78,423,'EDIT','123Acronym','acronym_project_format_KO'),
    Array('project','acronym_project',78,424,'EDIT','acrónimos','acronym_project_format_KO'),
    Array('project','acronym_project',78,425,'EDIT','acrónimos.c','acronym_project_format_KO'),
    Array('project','acronym_project',78,426,'EDIT','tu acronimo','acronym_project_format_KO'),
    Array('project','acronym_project',78,427,'EDIT','acrónimo 1','acronym_project_format_KO'),
    Array('project','acronym_project',78,428,'EDIT','1234567890','acronym_project_format_KO'),
    Array('project','acronym_project',78,429,'EDIT','acrónimo con ñ','acronym_project_format_KO'),
    Array('project','acronym_project',79,430,'EDIT','.,;:()[]-¡!¿?-"',true),
    Array('project','acronym_project',79,431,'EDIT','acronimo',true),
    Array('project','acronym_project',79,432,'EDIT','ACRONIMO',true),
    Array('project','acronym_project',79,433,'EDIT','acronimo.',true),
    Array('project','acronym_project',79,434,'EDIT','acroñimo',true),
    Array('project','acronym_project',79,435,'EDIT','ACRONIMO!',true),
    // Pruebas del campo acronym_project (SEARCH)
    Array('project','acronym_project',80,436,'SEARCH','a'.repeat(16),'acronym_project_max_size_KO'),
    Array('project','acronym_project',80,437,'SEARCH','a'.repeat(17),'acronym_project_max_size_KO'),
    Array('project','acronym_project',80,438,'SEARCH','a'.repeat(18),'acronym_project_max_size_KO'),
    Array('project','acronym_project',80,439,'SEARCH','a'.repeat(19),'acronym_project_max_size_KO'),
    Array('project','acronym_project',80,440,'SEARCH','a'.repeat(20),'acronym_project_max_size_KO'),
    Array('project','acronym_project',81,441,'SEARCH','123Acronym','acronym_project_format_KO'),
    Array('project','acronym_project',81,442,'SEARCH','acrónimos','acronym_project_format_KO'),
    Array('project','acronym_project',81,443,'SEARCH','acrónimos.c','acronym_project_format_KO'),
    Array('project','acronym_project',81,444,'SEARCH','tu acronimo','acronym_project_format_KO'),
    Array('project','acronym_project',81,445,'SEARCH','acrónimo 1','acronym_project_format_KO'),
    Array('project','acronym_project',81,446,'SEARCH','1234567890','acronym_project_format_KO'),
    Array('project','acronym_project',81,447,'SEARCH','acrónimo con ñ','acronym_project_format_KO'),
    Array('project','acronym_project',82,448,'SEARCH','.,;:()[]-¡!¿?-"',true),
    Array('project','acronym_project',82,449,'SEARCH','acronimo',true),
    Array('project','acronym_project',82,450,'SEARCH','ACRONIMO',true),
    Array('project','acronym_project',82,451,'SEARCH','acronimo.',true),
    Array('project','acronym_project',82,452,'SEARCH','acroñimo',true),
    Array('project','acronym_project',82,453,'SEARCH','ACRONIMO!',true),

    // Pruebas del campo id_sampling_methodology (ADD)
    Array('project','id_sampling_methodology',83,454,'ADD','','id_sampling_methodology_min_size_KO'),
    Array('project','id_sampling_methodology',84,455,'ADD','1'.repeat(12),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',84,456,'ADD','123456789012','id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',84,457,'ADD','1'.repeat(13),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',84,458,'ADD','1'.repeat(15),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',84,459,'ADD','1'.repeat(20),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',84,460,'ADD','1'.repeat(50),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',84,461,'ADD','1'.repeat(100),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',85,462,'ADD','abcdef','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',85,463,'ADD','1 1 1 1','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',85,464,'ADD','áéíóú','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',85,465,'ADD','ÁÉÍÓÚ','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',85,466,'ADD','1ñ7','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',85,467,'ADD','1.2.3.4.5','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',85,468,'ADD','ññññññ','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',85,469,'ADD','1.ñá7','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',85,470,'ADD','a b c d e','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',85,471,'ADD','123456!','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',86,472,'ADD','123456',true),
    Array('project','id_sampling_methodology',86,473,'ADD','1',true),
    Array('project','id_sampling_methodology',86,474,'ADD','111111',true),
    Array('project','id_sampling_methodology',86,475,'ADD','1'.repeat(11),true),
    Array('project','id_sampling_methodology',86,476,'ADD','12345678901',true),
    // Pruebas del campo id_sampling_methodology (EDIT)
    Array('project','id_sampling_methodology',87,477,'EDIT','','id_sampling_methodology_min_size_KO'),
    Array('project','id_sampling_methodology',88,478,'EDIT','1'.repeat(12),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',88,479,'EDIT','123456789012','id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',88,480,'EDIT','1'.repeat(13),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',88,481,'EDIT','1'.repeat(15),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',88,482,'EDIT','1'.repeat(20),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',88,483,'EDIT','1'.repeat(50),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',88,484,'EDIT','1'.repeat(100),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',89,485,'EDIT','abcdef','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',89,486,'EDIT','1 1 1 1','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',89,487,'EDIT','áéíóú','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',89,488,'EDIT','ÁÉÍÓÚ','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',89,489,'EDIT','1ñ7','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',89,490,'EDIT','1.2.3.4.5','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',89,491,'EDIT','ññññññ','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',89,492,'EDIT','1.ñá7','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',89,493,'EDIT','a b c d e','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',89,494,'EDIT','123456!','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',90,495,'EDIT','123456',true),
    Array('project','id_sampling_methodology',90,496,'EDIT','1',true),
    Array('project','id_sampling_methodology',90,497,'EDIT','111111',true),
    Array('project','id_sampling_methodology',90,498,'EDIT','1'.repeat(11),true),
    Array('project','id_sampling_methodology',90,499,'EDIT','12345678901',true),
    // Pruebas del campo id_sampling_methodology (SEARCH)
    Array('project','id_sampling_methodology',91,500,'SEARCH','1'.repeat(12),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',91,501,'SEARCH','123456789012','id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',91,502,'SEARCH','1'.repeat(13),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',91,503,'SEARCH','1'.repeat(15),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',91,504,'SEARCH','1'.repeat(20),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',91,505,'SEARCH','1'.repeat(50),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',91,506,'SEARCH','1'.repeat(100),'id_sampling_methodology_max_size_KO'),
    Array('project','id_sampling_methodology',92,507,'SEARCH','abcdef','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',92,508,'SEARCH','1 1 1 1','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',92,509,'SEARCH','áéíóú','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',92,510,'SEARCH','ÁÉÍÓÚ','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',92,511,'SEARCH','1ñ7','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',92,512,'SEARCH','1.2.3.4.5','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',92,513,'SEARCH','ññññññ','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',92,514,'SEARCH','1.ñá7','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',92,515,'SEARCH','a b c d e','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',92,516,'SEARCH','123456!','id_sampling_methodology_digits_KO'),
    Array('project','id_sampling_methodology',93,517,'SEARCH','123456',true),
    Array('project','id_sampling_methodology',93,518,'SEARCH','1',true),
    Array('project','id_sampling_methodology',93,519,'SEARCH','111111',true),
    Array('project','id_sampling_methodology',93,520,'SEARCH','1'.repeat(11),true),
    Array('project','id_sampling_methodology',93,521,'SEARCH','12345678901',true),

    //Pruebas del campo file_project (SEARCH)
    Array('project','file_project',94,522,'SEARCH','11nval1dname','file_project_format_name_file_KO'),
    Array('project','file_project',94,523,'SEARCH','áááááááááááá','file_project_format_name_file_KO'),
    Array('project','file_project',94,524,'SEARCH','invalid ñ name','file_project_format_name_file_KO'),
    Array('project','file_project',94,525,'SEARCH','inválid ñ name','file_project_format_name_file_KO'),
    Array('project','file_project',94,526,'SEARCH','invalid name','file_project_format_name_file_KO'),
    Array('project','file_project',95,527,'SEARCH','a'.repeat(101),'file_project_max_size_name_KO'),
    Array('project','file_project',95,528,'SEARCH','a'.repeat(102),'file_project_max_size_name_KO'),
    Array('project','file_project',95,529,'SEARCH','a'.repeat(103),'file_project_max_size_name_KO'),
    Array('project','file_project',95,530,'SEARCH','a'.repeat(104),'file_project_max_size_name_KO'),
    Array('project','file_project',95,531,'SEARCH','a'.repeat(105),'file_project_max_size_name_KO'),
    Array('project','file_project',95,532,'SEARCH','a'.repeat(106),'file_project_max_size_name_KO'),
    Array('project','file_project',96,533,'SEARCH','validfile.pdf',true),
    Array('project','file_project',96,534,'SEARCH','valid.file.pdf',true)
);

let pruebas_file_project = Array(
    //ADD
    Array('project','nuevo_file_project',97,535,'ADD','existe',Array(),'file_project_empty_KO'),
    Array('project','nuevo_file_project',98,536,'ADD','name_file',Array('11nval1dname',Array('application/pdf'),2000000),'file_project_format_name_file_KO'),
    Array('project','nuevo_file_project',98,537,'ADD','name_file',Array('áááááááááááá',Array('application/pdf'),2000000),'file_project_format_name_file_KO'),
    Array('project','nuevo_file_project',98,538,'ADD','name_file',Array('invalid ñ name',Array('application/pdf'),2000000),'file_project_format_name_file_KO'),
    Array('project','nuevo_file_project',98,539,'ADD','name_file',Array('inválid ñ name',Array('application/pdf'),2000000),'file_project_format_name_file_KO'),
    Array('project','nuevo_file_project',98,540,'ADD','name_file',Array('invalid name',Array('application/pdf'),2000000),'file_project_format_name_file_KO'),
    Array('project','nuevo_file_project',99,541,'ADD','type_file',Array('validname',Array('image/jpeg'),2000000),'file_project_type_file_KO'),
    Array('project','nuevo_file_project',99,542,'ADD','type_file',Array('validname',Array('image/jpg'),2000000),'file_project_type_file_KO'),
    Array('project','nuevo_file_project',99,543,'ADD','type_file',Array('validname',Array('image/bmp'),2000000),'file_project_type_file_KO'),
    Array('project','nuevo_file_project',99,544,'ADD','type_file',Array('validname',Array('appliciation/json'),2000000),'file_project_type_file_KO'),
    Array('project','nuevo_file_project',99,545,'ADD','type_file',Array('validname',Array('appliciation/csv'),2000000),'file_project_type_file_KO'),
    Array('project','nuevo_file_project',99,546,'ADD','type_file',Array('validname',Array('appliciation/txt'),2000000),'file_project_type_file_KO'),
    Array('project','nuevo_file_project',99,547,'ADD','type_file',Array('validname',Array('appliciation/xml'),2000000),'file_project_type_file_KO'),
    Array('project','nuevo_file_project',100,548,'ADD','max_size_file',Array('validname',Array('application/pdf'),2000001),'file_project_max_size_file_KO'),
    Array('project','nuevo_file_project',100,549,'ADD','max_size_file',Array('validname',Array('application/pdf'),2000002),'file_project_max_size_file_KO'),
    Array('project','nuevo_file_project',100,550,'ADD','max_size_file',Array('validname',Array('application/pdf'),2000003),'file_project_max_size_file_KO'),
    Array('project','nuevo_file_project',100,551,'ADD','max_size_file',Array('validname',Array('application/pdf'),2000004),'file_project_max_size_file_KO'),
    Array('project','nuevo_file_project',100,552,'ADD','max_size_file',Array('validname',Array('application/pdf'),20000000),'file_project_max_size_file_KO'),
    Array('project','nuevo_file_project',100,553,'ADD','max_size_file',Array('validname',Array('application/pdf'),200000000),'file_project_max_size_file_KO'),
    Array('project','nuevo_file_project',101,554,'ADD','min_size_name',Array('aaaaaa',Array('application/pdf'),2000000),'file_project_min_size_name_KO'),
    Array('project','nuevo_file_project',101,555,'ADD','min_size_name',Array('aaaaa',Array('application/pdf'),2000000),'file_project_min_size_name_KO'),
    Array('project','nuevo_file_project',101,556,'ADD','min_size_name',Array('aaaa',Array('application/pdf'),2000000),'file_project_min_size_name_KO'),
    Array('project','nuevo_file_project',101,557,'ADD','min_size_name',Array('aaa',Array('application/pdf'),2000000),'file_project_min_size_name_KO'),
    Array('project','nuevo_file_project',101,558,'ADD','min_size_name',Array('aa',Array('application/pdf'),2000000),'file_project_min_size_name_KO'),
    Array('project','nuevo_file_project',101,559,'ADD','min_size_name',Array('a',Array('application/pdf'),2000000),'file_project_min_size_name_KO'),
    Array('project','nuevo_file_project',102,560,'ADD','max_size_name',Array('a'.repeat(101),Array('application/pdf'),2000000),'file_project_max_size_name_KO'),
    Array('project','nuevo_file_project',102,561,'ADD','max_size_name',Array('a'.repeat(102),Array('application/pdf'),2000000),'file_project_max_size_name_KO'),
    Array('project','nuevo_file_project',102,562,'ADD','max_size_name',Array('a'.repeat(103),Array('application/pdf'),2000000),'file_project_max_size_name_KO'),
    Array('project','nuevo_file_project',102,563,'ADD','max_size_name',Array('a'.repeat(104),Array('application/pdf'),2000000),'file_project_max_size_name_KO'),
    Array('project','nuevo_file_project',102,564,'ADD','max_size_name',Array('a'.repeat(105),Array('application/pdf'),2000000),'file_project_max_size_name_KO'),
    Array('project','nuevo_file_project',102,565,'ADD','max_size_name',Array('a'.repeat(106),Array('application/pdf'),2000000),'file_project_max_size_name_KO'),
    Array('project','nuevo_file_project',103,566,'ADD','fichero ok',Array('validfile',Array('application/pdf'),2000000),true),
    Array('project','nuevo_file_project',103,567,'ADD','fichero ok',Array('valid.file',Array('application/pdf'),2000000),true),

    //EDIT
    Array('project','nuevo_file_project',104,568,'EDIT','existe',Array(),true),
    Array('project','nuevo_file_project',105,569,'EDIT','name_file',Array('11nval1dname',Array('application/pdf'),2000000),'file_project_format_name_file_KO'),
    Array('project','nuevo_file_project',105,570,'EDIT','name_file',Array('áááááááááááá',Array('application/pdf'),2000000),'file_project_format_name_file_KO'),
    Array('project','nuevo_file_project',105,571,'EDIT','name_file',Array('invalid ñ name',Array('application/pdf'),2000000),'file_project_format_name_file_KO'),
    Array('project','nuevo_file_project',105,572,'EDIT','name_file',Array('inválid ñ name',Array('application/pdf'),2000000),'file_project_format_name_file_KO'),
    Array('project','nuevo_file_project',105,573,'EDIT','name_file',Array('invalid name',Array('application/pdf'),2000000),'file_project_format_name_file_KO'),
    Array('project','nuevo_file_project',106,574,'EDIT','type_file',Array('validname',Array('image/jpeg'),2000000),'file_project_type_file_KO'),
    Array('project','nuevo_file_project',106,575,'EDIT','type_file',Array('validname',Array('image/jpg'),2000000),'file_project_type_file_KO'),
    Array('project','nuevo_file_project',106,576,'EDIT','type_file',Array('validname',Array('image/bmp'),2000000),'file_project_type_file_KO'),
    Array('project','nuevo_file_project',106,577,'EDIT','type_file',Array('validname',Array('appliciation/json'),2000000),'file_project_type_file_KO'),
    Array('project','nuevo_file_project',106,578,'EDIT','type_file',Array('validname',Array('appliciation/csv'),2000000),'file_project_type_file_KO'),
    Array('project','nuevo_file_project',106,579,'EDIT','type_file',Array('validname',Array('appliciation/txt'),2000000),'file_project_type_file_KO'),
    Array('project','nuevo_file_project',106,580,'EDIT','type_file',Array('validname',Array('appliciation/xml'),2000000),'file_project_type_file_KO'),
    Array('project','nuevo_file_project',107,581,'EDIT','max_size_file',Array('validname',Array('application/pdf'),2000001),'file_project_max_size_file_KO'),
    Array('project','nuevo_file_project',107,582,'EDIT','max_size_file',Array('validname',Array('application/pdf'),2000002),'file_project_max_size_file_KO'),
    Array('project','nuevo_file_project',107,583,'EDIT','max_size_file',Array('validname',Array('application/pdf'),2000003),'file_project_max_size_file_KO'),
    Array('project','nuevo_file_project',107,584,'EDIT','max_size_file',Array('validname',Array('application/pdf'),2000004),'file_project_max_size_file_KO'),
    Array('project','nuevo_file_project',107,585,'EDIT','max_size_file',Array('validname',Array('application/pdf'),20000000),'file_project_max_size_file_KO'),
    Array('project','nuevo_file_project',107,586,'EDIT','max_size_file',Array('validname',Array('application/pdf'),200000000),'file_project_max_size_file_KO'),
    Array('project','nuevo_file_project',108,587,'EDIT','min_size_name',Array('aaaaaa',Array('application/pdf'),2000000),'file_project_min_size_name_KO'),
    Array('project','nuevo_file_project',108,588,'EDIT','min_size_name',Array('aaaaa',Array('application/pdf'),2000000),'file_project_min_size_name_KO'),
    Array('project','nuevo_file_project',108,589,'EDIT','min_size_name',Array('aaaa',Array('application/pdf'),2000000),'file_project_min_size_name_KO'),
    Array('project','nuevo_file_project',108,590,'EDIT','min_size_name',Array('aaa',Array('application/pdf'),2000000),'file_project_min_size_name_KO'),
    Array('project','nuevo_file_project',108,591,'EDIT','min_size_name',Array('aa',Array('application/pdf'),2000000),'file_project_min_size_name_KO'),
    Array('project','nuevo_file_project',108,592,'EDIT','min_size_name',Array('a',Array('application/pdf'),2000000),'file_project_min_size_name_KO'),
    Array('project','nuevo_file_project',109,593,'EDIT','max_size_name',Array('a'.repeat(101),Array('application/pdf'),2000000),'file_project_max_size_name_KO'),
    Array('project','nuevo_file_project',109,594,'EDIT','max_size_name',Array('a'.repeat(102),Array('application/pdf'),2000000),'file_project_max_size_name_KO'),
    Array('project','nuevo_file_project',109,595,'EDIT','max_size_name',Array('a'.repeat(103),Array('application/pdf'),2000000),'file_project_max_size_name_KO'),
    Array('project','nuevo_file_project',109,596,'EDIT','max_size_name',Array('a'.repeat(104),Array('application/pdf'),2000000),'file_project_max_size_name_KO'),
    Array('project','nuevo_file_project',109,597,'EDIT','max_size_name',Array('a'.repeat(105),Array('application/pdf'),2000000),'file_project_max_size_name_KO'),
    Array('project','nuevo_file_project',109,598,'EDIT','max_size_name',Array('a'.repeat(106),Array('application/pdf'),2000000),'file_project_max_size_name_KO'),
    Array('project','nuevo_file_project',110,599,'EDIT','fichero ok',Array('validfile',Array('application/pdf'),2000000),true),
    Array('project','nuevo_file_project',110,600,'EDIT','fichero ok',Array('valid.file',Array('application/pdf'),2000000),true)
);