let def_tests_analysis_preparation = Array(
    // id_analysis_preparation
    Array('analysis_preparation','id_analysis_preparation',1,'cumple tamaño maximo','SEARCH','id_analysis_preparation_max_size_KO','Tamaño muy grande. El ID no puede tener más de 11 caracteres'),
    Array('analysis_preparation','id_analysis_preparation',2,'cumple formato','SEARCH','id_analysis_preparation_format_KO','Formato invalido. El ID contiene caracteres no permitidos (solo dígitos)'),
    Array('analysis_preparation','id_analysis_preparation',3,'es correcto','SEARCH',true,'ID correcto'),
    // name_analysis_preparation
    Array('analysis_preparation','name_analysis_preparation',4,'cumple tamaño minimo','ADD','name_analysis_preparation_min_size_KO','Tamaño demasiado corto. Debe tener al menos 8 caracteres'),
    Array('analysis_preparation','name_analysis_preparation',5,'cumple tamaño maximo','ADD','name_analysis_preparation_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 100 caracteres'),
    Array('analysis_preparation','name_analysis_preparation',6,'cumple formato','ADD','name_analysis_preparation_format_KO','Formato invalido. Solo se permiten caracteres alfabeticos y espacios, sin acentos ni ñ'),
    Array('analysis_preparation','name_analysis_preparation',7,'es correcto','ADD',true,'Nombre correcto'),
    Array('analysis_preparation','name_analysis_preparation',8,'cumple tamaño minimo','EDIT','name_analysis_preparation_min_size_KO','Tamaño demasiado corto. Debe tener al menos 8 caracteres'),
    Array('analysis_preparation','name_analysis_preparation',9,'cumple tamaño maximo','EDIT','name_analysis_preparation_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 100 caracteres'),
    Array('analysis_preparation','name_analysis_preparation',10,'cumple formato','EDIT','name_analysis_preparation_format_KO','Formato invalido. Solo se permiten caracteres alfabeticos y espacios, sin acentos ni ñ'),
    Array('analysis_preparation','name_analysis_preparation',11,'es correcto','EDIT',true,'Nombre correcto'),
    Array('analysis_preparation','name_analysis_preparation',12,'cumple tamaño maximo','SEARCH','name_analysis_preparation_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 100 caracteres'),
    Array('analysis_preparation','name_analysis_preparation',13,'cumple formato','SEARCH','name_analysis_preparation_format_KO','Formato invalido. Solo se permiten caracteres alfabeticos y espacios, sin acentos ni ñ'),
    Array('analysis_preparation','name_analysis_preparation',14,'es correcto','SEARCH',true,'Nombre correcto'),
    // description_analysis_preparation
    Array('analysis_preparation','description_analysis_preparation',15,'cumple tamaño mínimo','ADD','description_analysis_preparation_min_size_KO','Tamaño demasiado corto. Debe tener al menos 80 caracteres'),
    Array('analysis_preparation','description_analysis_preparation',16,'cumple tamaño máximo','ADD','description_analysis_preparation_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 5000 caracteres'),
    Array('analysis_preparation','description_analysis_preparation',17,'cumple formato','ADD','description_analysis_preparation_format_KO','Formato invalido. Solo se permiten caracteres alfabeticos y espacios, sin acentos ni ñ'),
    Array('analysis_preparation','description_analysis_preparation',18,'es correcto','ADD',true,'Descripcion correcta'),
    Array('analysis_preparation','description_analysis_preparation',19,'cumple tamaño mínimo','EDIT','description_analysis_preparation_min_size_KO','Tamaño demasiado corto. Debe tener al menos 80 caracteres'),
    Array('analysis_preparation','description_analysis_preparation',20,'cumple tamaño máximo','EDIT','description_analysis_preparation_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 5000 caracteres'),
    Array('analysis_preparation','description_analysis_preparation',21,'cumple formato','EDIT','description_analysis_preparation_format_KO','Formato invalido. Solo se permiten caracteres alfabeticos y espacios, sin acentos ni ñ'),
    Array('analysis_preparation','description_analysis_preparation',22,'es correcto','EDIT',true,'Descripcion correcta'),
    Array('analysis_preparation','description_analysis_preparation',23,'cumple tamaño máximo','SEARCH','description_analysis_preparation_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 5000 caracteres'),
    Array('analysis_preparation','description_analysis_preparation',24,'cumple formato','SEARCH','description_analysis_preparation_format_KO','Formato invalido. Solo se permiten caracteres alfabeticos y espacios, sin acentos ni ñ'),
    Array('analysis_preparation','description_analysis_preparation',25,'es correcto','SEARCH',true,'Descripcion correcta'),
    // bib_analysis_preparation
    Array('analysis_preparation','bib_analysis_preparation',26,'cumple tamaño mínimo','ADD','bib_analysis_preparation_min_size_KO','Tamaño demasiado corto. Debe tener al menos 6 caracteres'),
    Array('analysis_preparation','bib_analysis_preparation',27,'cumple tamaño máximo','ADD','bib_analysis_preparation_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 200 caracteres'),
    Array('analysis_preparation','bib_analysis_preparation',28,'cumple formato','ADD','bib_analysis_preparation_format_KO', 'Formato invalido. Se permiten caracteres alfabéticos con acentos, ñ, espacios y signos de puntuación'),
    Array('analysis_preparation','bib_analysis_preparation',29,'es correcto','ADD',true,'Bibliografia correcta'),
    Array('analysis_preparation','bib_analysis_preparation',30,'cumple tamaño mínimo','EDIT','bib_analysis_preparation_min_size_KO','Tamaño demasiado corto. Debe tener al menos 6 caracteres'),
    Array('analysis_preparation','bib_analysis_preparation',31,'cumple tamaño máximo','EDIT','bib_analysis_preparation_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 200 caracteres'),
    Array('analysis_preparation','bib_analysis_preparation',32,'cumple formato','EDIT','bib_analysis_preparation_format_KO', 'Formato invalido. Se permiten caracteres alfabéticos con acentos, ñ, espacios y signos de puntuación'),
    Array('analysis_preparation','bib_analysis_preparation',33,'es correcto','EDIT',true,'Bibliografia correcta'),
    Array('analysis_preparation','bib_analysis_preparation',34,'cumple tamaño máximo','SEARCH','bib_analysis_preparation_max_size_KO','Tamaño demasiado grande. Debe tener como máximo 200 caracteres'),
    Array('analysis_preparation','bib_analysis_preparation',35,'cumple formato','SEARCH','bib_analysis_preparation_format_KO', 'Formato invalido. Se permiten caracteres alfabéticos con acentos, ñ, espacios y signos de puntuación'),
    Array('analysis_preparation','bib_analysis_preparation',36,'es correcto','SEARCH',true,'Bibliografia correcta'),
    // file_analysis_preparation
    Array('analysis_preparation','file_analysis_preparation',37,'cumple nombre fichero','SEARCH','file_analysis_preparation_format_name_file_KO','El nombre del fichero no cumple el formato'),
    Array('analysis_preparation','file_analysis_preparation',38,'cumple tamaño máximo nombre fichero','SEARCH','file_analysis_preparation_max_size_name_KO','El tamaño del nombre del fichero es muy grande. Debe tener como máximo 100 caracteres'),
    Array('analysis_preparation','file_analysis_preparation',39,'fichero ok','SEARCH',true,'OK.'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',40,'existe fichero','ADD','nuevo_file_analysis_preparation_empty_KO','El fichero no existe. Debe subir un archivo'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',41,'cumple nombre fichero','ADD','nuevo_file_analysis_preparation_format_name_file_KO','El nombre del fichero no cumple el formato'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',42,'cumple tipo fichero','ADD','nuevo_file_analysis_preparation_type_file_KO','El tipo de fichero no está permitido. Solo se aceptan .pdf, .doc o .docx'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',43,'cumple tamaño máximo fichero','ADD','nuevo_file_analysis_preparation_max_size_file_KO','El tamaño del fichero es muy grande. No debe superar los 2 MB'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',44,'cumple tamaño mínimo nombre fichero','ADD','nuevo_file_analysis_preparation_min_size_name_KO','El tamaño del nombre del fichero es muy pequeño. Debe tener al menos 7 caracteres'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',45,'cumple tamaño máximo nombre fichero','ADD','nuevo_file_analysis_preparation_max_size_name_KO','El tamaño del nombre del fichero es muy grande. Debe tener como máximo 100 caracteres'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',46,'fichero ok','ADD', true, 'Fichero correcto'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',47,'no existe fichero','EDIT', true,'OK.'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',48,'cumple nombre fichero','EDIT','nuevo_file_analysis_preparation_format_name_file_KO','El nombre del fichero no cumple el formato'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',49,'cumple tipo fichero','EDIT','nuevo_file_analysis_preparation_type_file_KO','El tipo de fichero no está permitido. Solo se aceptan .pdf, .doc o .docx'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',50,'cumple tamaño máximo fichero','EDIT','nuevo_file_analysis_preparation_max_size_file_KO','El tamaño del fichero es muy grande. No debe superar los 2 MB'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',51,'cumple tamaño mínimo nombre fichero','EDIT','nuevo_file_analysis_preparation_min_size_name_KO','El tamaño del nombre del fichero es muy pequeño. Debe tener al menos 7 caracteres'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',52,'cumple tamaño máximo nombre fichero','EDIT','nuevo_file_analysis_preparation_max_size_name_KO','El tamaño del nombre del fichero es muy grande. Debe tener como máximo 100 caracteres'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',53,'fichero ok','EDIT',true,'OK.')
);

let pruebas_analysis_preparation = Array(
    // Pruebas del campo id_analysis_preparation (SEARCH)
    Array('analysis_preparation','id_analysis_preparation',1,1,'SEARCH','1'.repeat(12),'id_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','id_analysis_preparation',1,2,'SEARCH','1'.repeat(13),'id_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','id_analysis_preparation',1,3,'SEARCH','1'.repeat(14),'id_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','id_analysis_preparation',1,4,'SEARCH','1'.repeat(15),'id_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','id_analysis_preparation',1,5,'SEARCH','1'.repeat(20),'id_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','id_analysis_preparation',2,6,'SEARCH','abcdef','id_analysis_preparation_format_KO'),
    Array('analysis_preparation','id_analysis_preparation',2,7,'SEARCH','1ñ7','id_analysis_preparation_format_KO'),
    Array('analysis_preparation','id_analysis_preparation',2,8,'SEARCH','1 1 1 1','id_analysis_preparation_format_KO'),
    Array('analysis_preparation','id_analysis_preparation',2,9,'SEARCH','áéíóú','id_analysis_preparation_format_KO'),
    Array('analysis_preparation','id_analysis_preparation',2,10,'SEARCH','ÁÉÍÓÚ','id_analysis_preparation_format_KO'),
    Array('analysis_preparation','id_analysis_preparation',2,11,'SEARCH','1.2.3.4.5','id_analysis_preparation_format_KO'),
    Array('analysis_preparation','id_analysis_preparation',2,12,'SEARCH','ññññññ','id_analysis_preparation_format_KO'),
    Array('analysis_preparation','id_analysis_preparation',2,13,'SEARCH','1.ñá7','id_analysis_preparation_format_KO'),
    Array('analysis_preparation','id_analysis_preparation',2,14,'SEARCH','a b c d e','id_analysis_preparation_format_KO'),
    Array('analysis_preparation','id_analysis_preparation',2,15,'SEARCH','123456!','id_analysis_preparation_format_KO'),
    Array('analysis_preparation','id_analysis_preparation',3,16,'SEARCH','123456',true),
    Array('analysis_preparation','id_analysis_preparation',3,17,'SEARCH','1',true),
    Array('analysis_preparation','id_analysis_preparation',3,18,'SEARCH','111111',true),
    Array('analysis_preparation','id_analysis_preparation',3,19,'SEARCH','1'.repeat(11),true),
    Array('analysis_preparation','id_analysis_preparation',3,20,'SEARCH','12345678901',true),

    // Pruebas del campo name_analysis_preparation (ADD)
    Array('analysis_preparation','name_analysis_preparation',4,21,'ADD','a'.repeat(7),'name_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',4,22,'ADD','a'.repeat(6),'name_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',4,23,'ADD','a'.repeat(5),'name_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',4,24,'ADD','a'.repeat(4),'name_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',4,25,'ADD','a'.repeat(3),'name_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',4,26,'ADD','aa','name_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',4,27,'ADD','a','name_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',5,28,'ADD','a'.repeat(101),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',5,29,'ADD','a'.repeat(102),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',5,30,'ADD','a'.repeat(103),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',5,31,'ADD','a'.repeat(104),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',5,32,'ADD','a'.repeat(105),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',5,33,'ADD','a'.repeat(200),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',6,34,'ADD','á'.repeat(9),'name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',6,35,'ADD','Análisis1','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',6,36,'ADD','Añálisis1','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',6,37,'ADD','Anál.i.sis.1','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',6,38,'ADD','Análisis 1','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',6,39,'ADD','analisis-1','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',6,40,'ADD','Prueba Analisis Con Ñ','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',6,41,'ADD','Prueba Análisis Con Ñ','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',7,42,'ADD','Prueba Analisis',true),
    Array('analysis_preparation','name_analysis_preparation',7,43,'ADD','PRUEBA ANALISIS',true),
    Array('analysis_preparation','name_analysis_preparation',7,44,'ADD','ANALISISS',true),
    Array('analysis_preparation','name_analysis_preparation',7,45,'ADD','analisiss',true),
    // Pruebas del campo name_analysis_preparation (EDIT)
    Array('analysis_preparation','name_analysis_preparation',8,46,'EDIT','a'.repeat(7),'name_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',8,47,'EDIT','a'.repeat(6),'name_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',8,48,'EDIT','a'.repeat(5),'name_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',8,49,'EDIT','a'.repeat(4),'name_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',8,50,'EDIT','a'.repeat(3),'name_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',8,51,'EDIT','aa','name_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',8,52,'EDIT','a','name_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',9,53,'EDIT','a'.repeat(101),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',9,54,'EDIT','a'.repeat(102),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',9,55,'EDIT','a'.repeat(103),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',9,56,'EDIT','a'.repeat(104),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',9,57,'EDIT','a'.repeat(105),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',9,58,'EDIT','a'.repeat(200),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',10,59,'EDIT','á'.repeat(9),'name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',10,60,'EDIT','Análisis1','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',10,61,'EDIT','Añálisis1','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',10,62,'EDIT','Anál.i.sis.1','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',10,63,'EDIT','Análisis 1','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',10,64,'EDIT','analisis-1','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',10,65,'EDIT','Prueba Analisis Con Ñ','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',10,66,'EDIT','Prueba Análisis Con Ñ','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',11,67,'EDIT','Prueba Analisis',true),
    Array('analysis_preparation','name_analysis_preparation',11,68,'EDIT','PRUEBA ANALISIS',true),
    Array('analysis_preparation','name_analysis_preparation',11,69,'EDIT','ANALISISS',true),
    Array('analysis_preparation','name_analysis_preparation',11,70,'EDIT','analisiss',true),
    // Pruebas del campo name_analysis_preparation (SEARCH)
    Array('analysis_preparation','name_analysis_preparation',12,71,'SEARCH','a'.repeat(101),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',12,72,'SEARCH','a'.repeat(102),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',12,73,'SEARCH','a'.repeat(103),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',12,74,'SEARCH','a'.repeat(104),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',12,75,'SEARCH','a'.repeat(105),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',12,76,'SEARCH','a'.repeat(200),'name_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','name_analysis_preparation',13,77,'SEARCH','á'.repeat(9),'name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',13,78,'SEARCH','Análisis1','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',13,79,'SEARCH','Añálisis1','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',13,80,'SEARCH','Anál.i.sis.1','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',13,81,'SEARCH','Análisis 1','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',13,82,'SEARCH','analisis-1','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',13,83,'SEARCH','Prueba Analisis Con Ñ','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',13,84,'SEARCH','Prueba Análisis Con Ñ','name_analysis_preparation_format_KO'),
    Array('analysis_preparation','name_analysis_preparation',14,85,'SEARCH','Prueba Analisis',true),
    Array('analysis_preparation','name_analysis_preparation',14,86,'SEARCH','PRUEBA ANALISIS',true),
    Array('analysis_preparation','name_analysis_preparation',14,87,'SEARCH','ANALISISS',true),
    Array('analysis_preparation','name_analysis_preparation',14,88,'SEARCH','analisiss',true),

    // Pruebas del campo description_analysis_preparation (ADD)
    Array('analysis_preparation','description_analysis_preparation',15,89,'ADD','a'.repeat(79),'description_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',15,90,'ADD','a'.repeat(78),'description_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',15,91,'ADD','a'.repeat(70),'description_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',15,92,'ADD','a'.repeat(60),'description_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',15,93,'ADD','a'.repeat(10),'description_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',16,94,'ADD','a'.repeat(5001),'description_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',16,95,'ADD','a'.repeat(5002),'description_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',16,96,'ADD','a'.repeat(5005),'description_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',16,97,'ADD','a'.repeat(5010),'description_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',16,98,'ADD','a'.repeat(5050),'description_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',17,99,'ADD','ñ'.repeat(81),'description_analysis_preparation_format_KO'),
    Array('analysis_preparation','description_analysis_preparation',17,100,'ADD','la descripcion solo permite alfabéticos y no caracteres numericos como 1234567890','description_analysis_preparation_format_KO'),
    Array('analysis_preparation','description_analysis_preparation',17,101,'ADD','la descripcion solo permite alfabeticos, no caracteres numéricos como 123456789 ni simbolos como */','description_analysis_preparation_format_KO'),
    Array('analysis_preparation','description_analysis_preparation',17,102,'ADD','á'.repeat(81),'description_analysis_preparation_format_KO'),
    Array('analysis_preparation','description_analysis_preparation',18,103,'ADD','a'.repeat(81),true),
    Array('analysis_preparation','description_analysis_preparation',18,104,'ADD','a '.repeat(81),true),
    Array('analysis_preparation','description_analysis_preparation',18,105,'ADD','a '.repeat(40),true),
    // Pruebas del campo description_analysis_preparation (EDIT)
    Array('analysis_preparation','description_analysis_preparation',19,106,'EDIT','a'.repeat(79),'description_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',19,107,'EDIT','a'.repeat(78),'description_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',19,108,'EDIT','a'.repeat(70),'description_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',19,109,'EDIT','a'.repeat(60),'description_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',19,110,'EDIT','a'.repeat(10),'description_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',20,111,'EDIT','a'.repeat(5001),'description_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',20,112,'EDIT','a'.repeat(5002),'description_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',20,113,'EDIT','a'.repeat(5005),'description_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',20,114,'EDIT','a'.repeat(5010),'description_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',20,115,'EDIT','a'.repeat(5050),'description_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',21,116,'EDIT','ñ'.repeat(81),'description_analysis_preparation_format_KO'),
    Array('analysis_preparation','description_analysis_preparation',21,117,'EDIT','la descripcion solo permite alfabéticos y no caracteres numericos como 1234567890','description_analysis_preparation_format_KO'),
    Array('analysis_preparation','description_analysis_preparation',21,118,'EDIT','la descripcion solo permite alfabeticos, no caracteres numéricos como 123456789 ni simbolos como */','description_analysis_preparation_format_KO'),
    Array('analysis_preparation','description_analysis_preparation',21,119,'EDIT','á'.repeat(81),'description_analysis_preparation_format_KO'),
    Array('analysis_preparation','description_analysis_preparation',22,120,'EDIT','a'.repeat(81),true),
    Array('analysis_preparation','description_analysis_preparation',22,121,'EDIT','a '.repeat(81),true),
    Array('analysis_preparation','description_analysis_preparation',22,122,'EDIT','a '.repeat(40),true),
    // Pruebas del campo description_analysis_preparation (SEARCH)
    Array('analysis_preparation','description_analysis_preparation',23,123,'SEARCH','a'.repeat(5001),'description_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',23,124,'SEARCH','a'.repeat(5002),'description_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',23,125,'SEARCH','a'.repeat(5005),'description_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',23,126,'SEARCH','a'.repeat(5010),'description_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',23,127,'SEARCH','a'.repeat(5050),'description_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','description_analysis_preparation',24,128,'SEARCH','ñ'.repeat(81),'description_analysis_preparation_format_KO'),
    Array('analysis_preparation','description_analysis_preparation',24,129,'SEARCH','la descripcion solo permite alfabéticos y no caracteres numericos como 1234567890','description_analysis_preparation_format_KO'),
    Array('analysis_preparation','description_analysis_preparation',24,130,'SEARCH','la descripcion solo permite alfabeticos, no caracteres numéricos como 123456789 ni simbolos como */','description_analysis_preparation_format_KO'),
    Array('analysis_preparation','description_analysis_preparation',24,131,'SEARCH','á'.repeat(81),'description_analysis_preparation_format_KO'),
    Array('analysis_preparation','description_analysis_preparation',25,132,'SEARCH','a'.repeat(81),true),
    Array('analysis_preparation','description_analysis_preparation',25,133,'SEARCH','a '.repeat(81),true),
    Array('analysis_preparation','description_analysis_preparation',25,134,'SEARCH','a '.repeat(40),true),
    
    // Pruebas del campo bib_analysis_preparation (ADD)
    Array('analysis_preparation','bib_analysis_preparation',26,135,'ADD','a'.repeat(5),'bib_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',26,136,'ADD','a'.repeat(4),'bib_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',26,137,'ADD','aaa','bib_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',26,138,'ADD','aa','bib_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',26,139,'ADD','a','bib_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',27,140,'ADD','a'.repeat(201),'bib_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',27,141,'ADD','a'.repeat(202),'bib_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',27,142,'ADD','a'.repeat(205),'bib_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',27,143,'ADD','a'.repeat(300),'bib_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',27,144,'ADD','a'.repeat(500),'bib_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',28,145,'ADD','1111111111','bib_analysis_preparation_format_KO'),
    Array('analysis_preparation','bib_analysis_preparation',28,146,'ADD','b1bll1og4fí@','bib_analysis_preparation_format_KO'),
    Array('analysis_preparation','bib_analysis_preparation',28,147,'ADD','@@@@@@@','bib_analysis_preparation_format_KO'),
    Array('analysis_preparation','bib_analysis_preparation',29,148,'ADD','Bibliografía con acentos, ñ, espacios o .,;:()[]-¡!¿?-"',true),
    Array('analysis_preparation','bib_analysis_preparation',29,149,'ADD','Bibliografía con acentos, ñ, espacios o signos de puntuación y ü',true),
    Array('analysis_preparation','bib_analysis_preparation',29,150,'ADD','Bibliografíaconacentosñespaciososignosdepuntuación',true),
    Array('analysis_preparation','bib_analysis_preparation',29,151,'ADD','Bibliografía con acentos ñ espacios o signos de puntuación',true),
    // Pruebas del campo bib_analysis_preparation (EDIT)
    Array('analysis_preparation','bib_analysis_preparation',30,152,'EDIT','a'.repeat(5),'bib_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',30,153,'EDIT','a'.repeat(4),'bib_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',30,154,'EDIT','aaa','bib_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',30,155,'EDIT','aa','bib_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',30,156,'EDIT','a','bib_analysis_preparation_min_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',31,157,'EDIT','a'.repeat(201),'bib_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',31,158,'EDIT','a'.repeat(202),'bib_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',31,159,'EDIT','a'.repeat(205),'bib_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',31,160,'EDIT','a'.repeat(300),'bib_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',31,161,'EDIT','a'.repeat(500),'bib_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',32,162,'EDIT','1111111111','bib_analysis_preparation_format_KO'),
    Array('analysis_preparation','bib_analysis_preparation',32,163,'EDIT','b1bll1og4fí@','bib_analysis_preparation_format_KO'),
    Array('analysis_preparation','bib_analysis_preparation',32,164,'EDIT','@@@@@@@','bib_analysis_preparation_format_KO'),
    Array('analysis_preparation','bib_analysis_preparation',33,165,'EDIT','Bibliografía con acentos, ñ, espacios o .,;:()[]-¡!¿?-"',true),
    Array('analysis_preparation','bib_analysis_preparation',33,166,'EDIT','Bibliografía con acentos, ñ, espacios o signos de puntuación y ü',true),
    Array('analysis_preparation','bib_analysis_preparation',33,167,'EDIT','Bibliografíaconacentosñespaciososignosdepuntuación',true),
    Array('analysis_preparation','bib_analysis_preparation',33,168,'EDIT','Bibliografía con acentos ñ espacios o signos de puntuación',true),
    // Pruebas del campo bib_analysis_preparation (SEARCH)
    Array('analysis_preparation','bib_analysis_preparation',34,169,'SEARCH','a'.repeat(201),'bib_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',34,170,'SEARCH','a'.repeat(202),'bib_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',34,171,'SEARCH','a'.repeat(205),'bib_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',34,172,'SEARCH','a'.repeat(300),'bib_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',34,173,'SEARCH','a'.repeat(500),'bib_analysis_preparation_max_size_KO'),
    Array('analysis_preparation','bib_analysis_preparation',35,174,'SEARCH','1111111111','bib_analysis_preparation_format_KO'),
    Array('analysis_preparation','bib_analysis_preparation',35,175,'SEARCH','b1bll1og4fí@','bib_analysis_preparation_format_KO'),
    Array('analysis_preparation','bib_analysis_preparation',35,176,'SEARCH','@@@@@@@','bib_analysis_preparation_format_KO'),
    Array('analysis_preparation','bib_analysis_preparation',36,177,'SEARCH','Bibliografía con acentos, ñ, espacios o .,;:()[]-¡!¿?-")',true),
    Array('analysis_preparation','bib_analysis_preparation',36,178,'SEARCH','Bibliografía con acentos, ñ, espacios o signos de puntuación y ü',true),
    Array('analysis_preparation','bib_analysis_preparation',36,179,'SEARCH','Bibliografíaconacentosñespaciososignosdepuntuación',true),
    Array('analysis_preparation','bib_analysis_preparation',36,180,'SEARCH','Bibliografía con acentos ñ espacios o signos de puntuación',true),

    // Pruebas del campo file_analysis_preparation (SEARCH)
    Array('analysis_preparation','file_analysis_preparation',37,181,'SEARCH','11nval1dname','file_analysis_preparation_format_name_file_KO'),
    Array('analysis_preparation','file_analysis_preparation',37,182,'SEARCH','áááááááááááá','file_analysis_preparation_format_name_file_KO'),
    Array('analysis_preparation','file_analysis_preparation',37,183,'SEARCH','invalid ñ name','file_analysis_preparation_format_name_file_KO'),
    Array('analysis_preparation','file_analysis_preparation',37,184,'SEARCH','inválid ñ name','file_analysis_preparation_format_name_file_KO'),
    Array('analysis_preparation','file_analysis_preparation',37,185,'SEARCH','invalid name','file_analysis_preparation_format_name_file_KO'),
    Array('analysis_preparation','file_analysis_preparation',38,186,'SEARCH','a'.repeat(101),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','file_analysis_preparation',38,187,'SEARCH','a'.repeat(102),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','file_analysis_preparation',38,188,'SEARCH','a'.repeat(103),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','file_analysis_preparation',38,189,'SEARCH','a'.repeat(104),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','file_analysis_preparation',38,190,'SEARCH','a'.repeat(105),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','file_analysis_preparation',38,191,'SEARCH','a'.repeat(110),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','file_analysis_preparation',39,192,'SEARCH','validfile.pdf',true),
    Array('analysis_preparation','file_analysis_preparation',39,193,'SEARCH','valid.file',true)
);


let pruebas_file_analysis_preparation = Array(
    //ADD
    Array('analysis_preparation','nuevo_file_analysis_preparation',40,194,'ADD','existe',Array(),'file_analysis_preparation_empty_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',41,195,'ADD','name_file',Array('11nval1dname',Array('application/pdf'),2000000),'file_analysis_preparation_format_name_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',41,196,'ADD','name_file',Array('áááááááááááá',Array('application/pdf'),2000000),'file_analysis_preparation_format_name_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',41,197,'ADD','name_file',Array('invalid ñ name',Array('application/pdf'),2000000),'file_analysis_preparation_format_name_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',41,198,'ADD','name_file',Array('inválid ñ name',Array('application/pdf'),2000000),'file_analysis_preparation_format_name_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',41,199,'ADD','name_file',Array('invalid name',Array('application/pdf'),2000000),'file_analysis_preparation_format_name_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',42,200,'ADD','type_file',Array('validname',Array('image/jpeg'),2000000),'file_analysis_preparation_type_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',42,201,'ADD','type_file',Array('validname',Array('image/jpg'),2000000),'file_analysis_preparation_type_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',42,202,'ADD','type_file',Array('validname',Array('image/bmp'),2000000),'file_analysis_preparation_type_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',42,203,'ADD','type_file',Array('validname',Array('appliciation/json'),2000000),'file_analysis_preparation_type_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',42,204,'ADD','type_file',Array('validname',Array('appliciation/csv'),2000000),'file_analysis_preparation_type_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',42,205,'ADD','type_file',Array('validname',Array('appliciation/txt'),2000000),'file_analysis_preparation_type_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',42,206,'ADD','type_file',Array('validname',Array('appliciation/xml'),2000000),'file_analysis_preparation_type_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',43,207,'ADD','max_size_file',Array('validname',Array('application/pdf'),2000001),'file_analysis_preparation_max_size_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',43,208,'ADD','max_size_file',Array('validname',Array('application/pdf'),2000002),'file_analysis_preparation_max_size_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',44,209,'ADD','min_size_name',Array('aaaaaa',Array('application/pdf'),2000000),'file_analysis_preparation_min_size_name_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',44,210,'ADD','min_size_name',Array('aaaaa',Array('application/pdf'),2000000),'file_analysis_preparation_min_size_name_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',45,211,'ADD','max_size_name',Array('a'.repeat(101),Array('application/pdf'),2000000),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',45,212,'ADD','max_size_name',Array('a'.repeat(102),Array('application/pdf'),2000000),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',45,213,'ADD','max_size_name',Array('a'.repeat(103),Array('application/pdf'),2000000),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',45,214,'ADD','max_size_name',Array('a'.repeat(104),Array('application/pdf'),2000000),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',45,215,'ADD','max_size_name',Array('a'.repeat(105),Array('application/pdf'),2000000),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',45,216,'ADD','max_size_name',Array('a'.repeat(110),Array('application/pdf'),2000000),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',46,217,'ADD','fichero ok',Array('validfile',Array('application/pdf'),2000000),true),
    Array('analysis_preparation','nuevo_file_analysis_preparation',46,218,'ADD','fichero ok',Array('valid.file',Array('application/pdf'),2000000),true),
    //EDIT
    Array('analysis_preparation','nuevo_file_analysis_preparation',47,219,'EDIT','noexiste',Array(),true),
    Array('analysis_preparation','nuevo_file_analysis_preparation',48,220,'EDIT','name_file',Array('11nval1dname',Array('application/pdf'),2000000),'file_analysis_preparation_format_name_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',48,221,'EDIT','name_file',Array('áááááááááááá',Array('application/pdf'),2000000),'file_analysis_preparation_format_name_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',48,222,'EDIT','name_file',Array('invalid ñ name',Array('application/pdf'),2000000),'file_analysis_preparation_format_name_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',48,223,'EDIT','name_file',Array('inválid ñ name',Array('application/pdf'),2000000),'file_analysis_preparation_format_name_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',48,224,'EDIT','name_file',Array('invalid name',Array('application/pdf'),2000000),'file_analysis_preparation_format_name_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',49,225,'EDIT','type_file',Array('validname',Array('image/jpeg'),2000000),'file_analysis_preparation_type_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',49,226,'EDIT','type_file',Array('validname',Array('image/jpg'),2000000),'file_analysis_preparation_type_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',49,227,'EDIT','type_file',Array('validname',Array('image/bmp'),2000000),'file_analysis_preparation_type_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',49,228,'EDIT','type_file',Array('validname',Array('appliciation/json'),2000000),'file_analysis_preparation_type_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',49,229,'EDIT','type_file',Array('validname',Array('appliciation/csv'),2000000),'file_analysis_preparation_type_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',49,230,'EDIT','type_file',Array('validname',Array('appliciation/txt'),2000000),'file_analysis_preparation_type_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',49,231,'EDIT','type_file',Array('validname',Array('appliciation/xml'),2000000),'file_analysis_preparation_type_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',50,232,'EDIT','max_size_file',Array('validname',Array('application/pdf'),20000001),'file_analysis_preparation_max_size_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',50,233,'EDIT','max_size_file',Array('validname',Array('application/pdf'),20000002),'file_analysis_preparation_max_size_file_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',51,234,'EDIT','min_size_name',Array('aaaaaa',Array('application/pdf'),2000000),'file_analysis_preparation_min_size_name_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',51,235,'EDIT','min_size_name',Array('aaaaa',Array('application/pdf'),2000000),'file_analysis_preparation_min_size_name_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',52,236,'EDIT','max_size_name',Array('a'.repeat(101),Array('application/pdf'),2000000),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',52,237,'EDIT','max_size_name',Array('a'.repeat(102),Array('application/pdf'),2000000),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',52,238,'EDIT','max_size_name',Array('a'.repeat(103),Array('application/pdf'),2000000),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',52,239,'EDIT','max_size_name',Array('a'.repeat(104),Array('application/pdf'),2000000),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',52,240,'EDIT','max_size_name',Array('a'.repeat(105),Array('application/pdf'),2000000),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',52,241,'EDIT','max_size_name',Array('a'.repeat(110),Array('application/pdf'),2000000),'file_analysis_preparation_max_size_name_KO'),
    Array('analysis_preparation','nuevo_file_analysis_preparation',53,242,'EDIT','fichero ok',Array('validfile',Array('application/pdf'),2000000),true),
    Array('analysis_preparation','nuevo_file_analysis_preparation',53,243,'EDIT','fichero ok',Array('valid.file',Array('application/pdf'),2000000),true)
);