let textos_EN = {

	// title texts
	'text_titulo_app': 'ET2 UI Interface',
	'text_titulo_menu': 'Menu Options',
	'text_titulo_pie': 'Footer',
	'text_project': 'Projects',
	'text_analysis_prep': 'Analysis Preparations',
	'text_titulo_page_analysis_preparation': 'Analysis Preparation Management',
	'text_titulo_page_project': 'Project Management',
	'text_contenido_titulo_form_analysis_prep_ADD': 'Add Analysis Preparation Form',
	'text_contenido_titulo_form_analysis_prep_EDIT': 'Edit Analysis Preparation Form',
	'text_contenido_titulo_form_analysis_prep_SEARCH': 'Search Analysis Preparation Form',
	'text_contenido_titulo_form_analysis_prep_DELETE': 'Delete Analysis Preparation Form',
	'text_contenido_titulo_form_analysis_prep_SHOWCURRENT': 'Showcurrent Analysis Preparation Form',
	'text_contenido_titulo_form_project_ADD': 'Add Project Form',
	'text_contenido_titulo_form_project_EDIT': 'Edit Project Form',
	'text_contenido_titulo_form_project_SEARCH': 'Search Project Form',
	'text_contenido_titulo_form_project_DELETE': 'Delete Project Form',
	'text_contenido_titulo_form_project_SHOWCURRENT': 'Showcurrent Project Form',
	'resultadodef': 'Correct Format for Test Structure Definition',
	'resultadoprueba': 'Correct Format for Test Structure',
	'resultadotest': 'Test Execution Result',

	// atributes
	'id_analysis_preparation': 'Analysis Preparation ID',
	'name_analysis_preparation': 'Analysis Preparation Name',
	'description_analysis_preparation': 'Analysis Preparation Description',
	'bib_analysis_preparation': 'Analysis Preparation Bibliography',
	'file_analysis_preparation': 'Analysis Preparation File',
	'link_file_analysis_preparation': 'Analysis Preparation File Link',
    'nuevo_file_analysis_preparation': 'New Analysis Preparation File',
	'id_project': 'Project ID',
    'name_project': 'Project name',
    'start_date_project': 'Start date',
    'end_date_project': 'End date',
    'responsable_project': 'Project manager',
    'organization_project': 'Project organization',
    'description_project': 'Project description',
	'nuevo_file_project': 'Project file',
    'file_project': 'Project file',
    'code_project': 'Code',
    'acronym_project': 'Acronym',
    'id_sampling_methodology': 'Sampling methodology',
	'link_file_project': 'Project File Link',
    'nuevo_file_project': 'New Project File',

	// labels
	'label_id_analysis_preparation': 'Analysis Preparation ID',
	'label_name_analysis_preparation': 'Analysis Preparation Name',
	'label_description_analysis_preparation': 'Analysis Preparation Description',
	'label_bib_analysis_preparation': 'Analysis Preparation Bibliography',
	'label_file_analysis_preparation': 'Analysis Preparation File',
	'label_nuevo_file_analysis_preparation': 'New Analysis Preparation File',
    'label_id_project': 'Project identification',
    'label_name_project': 'Project name',
    'label_start_date_project': 'Start date',
    'label_end_date_project': 'End date',
    'label_responsable_project': 'Project manager',
    'label_organization_project': 'Project organization',
    'label_description_project': 'Project description',
	'label_nuevo_file_project': 'Project file',
    'label_file_project': 'Project file',
    'label_code_project': 'Code',
    'label_acronym_project': 'Acronym',
    'label_id_sampling_methodology': 'Sampling methodology',

	// form validation errors
	'id_analysis_preparation_min_size_KO': 'Number too short. It must have at least 1 digit',
    'id_analysis_preparation_max_size_KO': 'Number too long. It must have less than 11 digits',
    'id_analysis_preparation_format_KO': 'Invalid number. Only digits are allowed',

    'name_analysis_preparation_min_size_KO': 'Name too short. It must have at least 8 characters.',
    'name_analysis_preparation_max_size_KO': 'Name too long. It must have less than 100 characters.',
    'name_analysis_preparation_format_KO': 'Name contains invalid characters. Only letters and spaces are allowed, without accents or ñ.',

    'description_analysis_preparation_min_size_KO': 'Description too short. It must have at least 80 characters.',
    'description_analysis_preparation_max_size_KO': 'Description too long. It must have less than 5000 characters.',
    'description_analysis_preparation_format_KO': 'Description contains invalid characters. Only letters and spaces are allowed, without accents or ñ.',

    'bib_analysis_preparation_min_size_KO': 'Bibliography too short. It must have at least 6 characters.',
    'bib_analysis_preparation_max_size_KO': 'Bibliography too long. It must have less than 200 characters.',
    'bib_analysis_preparation_format_KO': 'Bibliography contains invalid characters. Only letters, accents, ñ, spaces, and punctuation marks are allowed.',

    'file_analysis_preparation_empty_KO': 'The file cannot be empty. A file must be uploaded.',
    'file_analysis_preparation_format_name_file_KO': 'The file name does not meet the allowed format.',
    'file_analysis_preparation_type_file_KO': 'The file type is not allowed. Only .pdf, .doc, or .docx are accepted.',
    'file_analysis_preparation_max_size_file_KO': 'The file exceeds the allowed size. Maximum 2 MB.',
    'file_analysis_preparation_min_size_name_KO': 'The file name is too short. It must have at least 7 characters.',
    'file_analysis_preparation_max_size_name_KO': 'The file name is too long. It must have less than 100 characters.',

    'nuevo_file_analysis_preparation_empty_KO': 'The file cannot be empty. A file must be uploaded.',
    'nuevo_file_analysis_preparation_format_name_file_KO': 'The file name does not meet the allowed format.',
    'nuevo_file_analysis_preparation_type_file_KO': 'The file type is not allowed. Only .pdf, .doc, or .docx are accepted.',
    'nuevo_file_analysis_preparation_max_size_file_KO': 'The file exceeds the allowed size. Maximum 2 MB.',
    'nuevo_file_analysis_preparation_min_size_name_KO': 'The file name is too short. It must have at least 7 characters.',
    'nuevo_file_analysis_preparation_max_size_name_KO': 'The file name is too long. It must have less than 100 characters.',

    'true': 'Success',

    'id_project_min_size_KO': 'Number too short. It must have at least 1 digit',
    'id_project_max_size_KO': 'Number too long. It must have less than 11 digits',
    'id_project_format_KO': 'Invalid number. Only digits are allowed',

    'name_project_min_size_KO': 'Name too short. It must have at least 15 characters.',
    'name_project_max_size_KO': 'Name too long. It must have less than 100 characters.',
    'name_project_format_KO': 'Invalid name. It must consist only of alphabetic characters without accents, ñ, or spaces.',

    'start_date_project_format_KO': 'Incorrect start date format. It must be dd/mm/yyyy.',
    'start_date_project_valid_KO': 'Invalid start date. It must be a valid date.',

    'end_date_project_format_KO': 'Incorrect end date format. It must be dd/mm/yyyy.',
    'end_date_project_valid_KO': 'Invalid end date. It must be a valid date.',

    'responsable_project_min_size_KO': 'Responsible too short. It must have at least 6 characters.',
    'responsable_project_max_size_KO': 'Responsible too long. It must have less than 60 characters.',
    'responsable_project_format_KO': 'Responsible with incorrect format. It must consist only of alphabetic characters with accents, ñ, and spaces.',

    'organization_project_min_size_KO': 'Organization too short. It must have at least 6 characters.',
    'organization_project_max_size_KO': 'Organization too long. It must have less than 100 characters.',
    'organization_project_format_KO': 'Organization with incorrect format. It must consist only of alphabetic characters with accents, ñ, and spaces.',

    'description_project_min_size_KO': 'Description too short. It must have at least 30 characters.',
    'description_project_max_size_KO': 'Description too long. It must have less than 500 characters.',

    'file_project_min_size_name_KO': 'File name too short. It must have at least 7 characters.',
    'file_project_max_size_name_KO': 'File name too long. It must have less than 100 characters.',
    'file_project_format_name_file_KO': 'File with incorrect format. It must consist only of alphabetic characters with accents, ñ, spaces, and punctuation marks.',
    'file_project_max_size_file_KO': 'File with incorrect size. It must have a size smaller than 2000000 bytes.',
    'file_project_type_file_KO': 'File with incorrect format. It must have a .pdf, .doc, or .docx extension.',

    'nuevo_file_project_min_size_name_KO': 'File name too short. It must have at least 7 characters.',
    'nuevo_file_project_max_size_name_KO': 'File name too long. It must have less than 100 characters.',
    'nuevo_file_project_format_name_file_KO': 'File with incorrect format. It must consist only of alphabetic characters with accents, ñ, spaces, and punctuation marks.',
    'nuevo_file_project_max_size_file_KO': 'File with incorrect size. It must have a size smaller than 2000000 bytes.',
    'nuevo_file_project_type_file_KO': 'File with incorrect format. It must have a .pdf, .doc, or .docx extension.',

    'code_project_min_size_KO': 'Code too short. It must have at least 6 characters.',
    'code_project_max_size_KO': 'Code too long. It must have less than 50 characters.',
    'code_project_format_KO': 'Code with incorrect format. It must consist only of alphabetic characters without accents, ñ, or spaces',

    'acronym_project_min_size_KO': 'Acronym too short. It must have at least 6 characters.',
    'acronym_project_max_size_KO': 'Acronym too long. It must have less than 15 characters.',
    'acronym_project_format_KO': 'Acronym with incorrect format. It must consist only of alphabetic characters with ñ and punctuation marks, without accents or spaces.',

    'id_sampling_methodology_min_size_KO': 'Number too short. It must have at least 1 digit',
    'id_sampling_methodology_max_size_KO': 'Number too long. It must have less than 11 digits',
    'id_sampling_methodology_format_KO': 'Invalid number. Only digits are allowed',

	//ERRORES BACK
	'id_analysis_preparation_es_nulo_KO': 'Analysis preparation ID is null. It was expected but not received',
    'name_analysis_preparation_es_nulo_KO': 'Analysis preparation name is null. It was expected but not received',
    'description_analysis_preparation_es_nulo_KO': 'Analysis preparation description is null. It was expected but not received',
    'bib_analysis_preparation_es_nulo_KO': 'Analysis preparation bibliography is null. It was expected but not received',
    'file_analysis_preparation_es_nulo_KO': 'No file was uploaded.',
    'id_project_es_nulo_KO': 'Project ID is null. It was expected but not received',
    'name_project_es_nulo_KO': 'Project name is null. It was expected but not received',
    'start_date_project_es_nulo_KO': 'Start date is null. It was expected but not received',
    'end_date_project_es_nulo_KO': 'End date is null. It was expected but not received',
    'responsable_project_es_nulo_KO': 'Project responsible is null. It was expected but not received',
    'organization_project_es_nulo_KO': 'Project organization is null. It was expected but not received',
    'description_project_es_nulo_KO': 'Project description is null. It was expected but not received',
    'nuevo_file_project_es_nulo_KO': 'New project file is null. It was expected but not received',
    'file_project_es_nulo_KO': 'Project file is null. It was expected but not received',
    'code_project_es_nulo_KO': 'Code is null. It was expected but not received',
    'acronym_project_es_nulo_KO': 'Acronym is null. It was expected but not received',
    'id_sampling_methodology_es_nulo_KO': 'Sampling methodology is null. It was expected but not received',
    'link_file_project_es_nulo_KO': 'Project file link is null. It was expected but not received',
    'SQL_OK': 'Operation completed successfully.',
    'SQL_KO': 'The operation failed due to an SQL error. Some data is not in the correct format.',
    'RECORDSET_VACIO': 'The search returned no results.',
    'RECORDSET_DATOS': 'The search returned data.'
}