let textos_ES = {

	// textos titulos
	'text_titulo_app': 'Interfaz ET2 IU',
	'text_titulo_menu': 'Opciones de Menú',
	'text_titulo_pie': 'Pie de página',
	'text_project': 'Proyectos',
	'text_analysis_prep': 'Preparaciones de Análisis',
	'text_titulo_page_analysis_preparation' : 'Gestión de Preparaciones de Análisis',
	'text_titulo_page_project' : 'Gestión de Proyectos',
	'text_contenido_titulo_form_analysis_prep_ADD': 'Formulario Alta Preparaciones de Análisis',
	'text_contenido_titulo_form_analysis_prep_EDIT': 'Formulario Modificación Preparaciones de Análisis',
	'text_contenido_titulo_form_analysis_prep_SEARCH': 'Formulario Búsqueda Preparaciones de Análisis',
	'text_contenido_titulo_form_analysis_prep_DELETE': 'Formulario Borrado Preparaciones de Análisis',
	'text_contenido_titulo_form_analysis_prep_SHOWCURRENT': 'Formulario Actual de Preparaciones de Análisis',
	'text_contenido_titulo_form_project_ADD': 'Formulario Alta Proyectos',
	'text_contenido_titulo_form_project_EDIT': 'Formulario Modificación Proyectos',
	'text_contenido_titulo_form_project_SEARCH': 'Formulario Búsqueda Proyectos',
	'text_contenido_titulo_form_project_DELETE': 'Formulario Borrado Proyectos',
	'text_contenido_titulo_form_project_SHOWCURRENT': 'Formulario Actual de Proyecto',
	'resultadodef': 'Formato correcto estructura definición tests',
	'resultadoprueba': 'Formato correcto estructura pruebas',
	'resultadotest':'Resultado ejecución pruebas',

	// atributos
	'id_analysis_preparation': 'Identificación de preparaciones de análisis',
	'name_analysis_preparation': 'Nombre de preparaciones de análisis',
	'description_analysis_preparation': 'Descripción de preparaciones de análisis',
	'bib_analysis_preparation': 'Bibliografía de preparaciones de análisis',
	'file_analysis_preparation': 'Archivo de preparaciones de análisis',
	'link_file_analysis_preparation': 'Link Archivo de Preparación de Análisis',
	'nuevo_file_analysis_preparation': 'Nuevo Archivo de Preparación de Análisis ',
	'id_project': 'Identificación de proyecto',
    'name_project': 'Nombre de proyecto',
    'start_date_project': 'Fecha de inicio',
    'end_date_project': 'Fecha de fin',
    'responsable_project': 'Responsable del proyecto',
    'organization_project': 'Organización del proyecto',
    'description_project': 'Descripción de proyecto',
	'nuevo_file_project': 'Archivo de proyecto',
    'file_project': 'Archivo de proyecto',
    'code_project': 'Código',
    'acronym_project': 'Acrónimo',
    'id_sampling_methodology': 'Metodología de muestreo',
	'link_file_project': 'Link Archivo de Proyecto',
	'nuevo_file_project': 'Nuevo Archivo de Proyecto',

	// labels
	'label_id_analysis_preparation': 'Identificación de preparaciones de análisis',
	'label_name_analysis_preparation': 'Nombre de preparaciones de análisis',
	'label_description_analysis_preparation': 'Descripción de preparaciones de análisis',
	'label_bib_analysis_preparation': 'Bibliografía de preparaciones de análisis',
	'label_file_analysis_preparation': 'Archivo de preparaciones de análisis',
	'label_nuevo_file_analysis_preparation': 'Nuevo archivo de preparaciones de análisis',
	'label_id_project': 'Identificación de proyecto',
    'label_name_project': 'Nombre de proyecto',
    'label_start_date_project': 'Fecha de inicio',
    'label_end_date_project': 'Fecha de fin',
    'label_responsable_project': 'Responsable del proyecto',
    'label_organization_project': 'Organización del proyecto',
    'label_description_project': 'Descripción de proyecto',
	'label_nuevo_file_project': 'Nuevo Archivo de proyecto',
    'label_file_project': 'Archivo de proyecto',
    'label_code_project': 'Código',
    'label_acronym_project': 'Acrónimo',
    'label_id_sampling_methodology': 'Metodología de muestreo',

	// errores validaciones formulario
	'id_analysis_preparation_min_size_KO': 'Número demasiado corto. Debe tener al menos 1 dígito',
	'id_analysis_preparation_max_size_KO': 'Número demasiado largo. Debe tener menos de 11 dígitos',
	'id_analysis_preparation_format_KO': 'Número no válido. Solo se permiten dígitos',

	'name_analysis_preparation_min_size_KO': 'El nombre es demasiado corto. Debe tener al menos 8 caracteres.',
    'name_analysis_preparation_max_size_KO': 'El nombre es demasiado largo. Debe tener menos de 100 caracteres.',
    'name_analysis_preparation_format_KO': 'El nombre contiene caracteres no válidos. Solo se permiten letras y espacios, sin acentos ni ñ.',

    'description_analysis_preparation_min_size_KO': 'La descripción es demasiado corta. Debe tener al menos 80 caracteres.',
    'description_analysis_preparation_max_size_KO': 'La descripción es demasiado larga. Debe tener menos de 5000 caracteres.',
    'description_analysis_preparation_format_KO': 'La descripción contiene caracteres no válidos. Solo se permiten letras y espacios, sin acentos ni ñ.',

    'bib_analysis_preparation_min_size_KO': 'La bibliografía es demasiado corta. Debe tener al menos 6 caracteres.',
    'bib_analysis_preparation_max_size_KO': 'La bibliografía es demasiado larga. Debe tener menos de 200 caracteres.',
    'bib_analysis_preparation_format_KO': 'La bibliografía contiene caracteres no válidos. Solo se permiten letras, acentos, ñ, espacios y signos de puntuación.',

    'file_analysis_preparation_empty_KO': 'El archivo no puede estar vacío. Debe subir un archivo.',
    'file_analysis_preparation_format_name_file_KO': 'El nombre del archivo no cumple el formato permitido.',
    'file_analysis_preparation_type_file_KO': 'El tipo de archivo no está permitido. Solo se aceptan .pdf, .doc o .docx.',
    'file_analysis_preparation_max_size_file_KO': 'El archivo excede el tamaño permitido. Máximo 2 MB.',
    'file_analysis_preparation_min_size_name_KO': 'El nombre del archivo es demasiado corto. Debe tener al menos 7 caracteres.',
    'file_analysis_preparation_max_size_name_KO': 'El nombre del archivo es demasiado largo. Debe tener menos de 100 caracteres.',

	'nuevo_file_analysis_preparation_empty_KO': 'El archivo no puede estar vacío. Debe subir un archivo.',
    'nuevo_file_analysis_preparation_format_name_file_KO': 'El nombre del archivo no cumple el formato permitido.',
    'nuevo_file_analysis_preparation_type_file_KO': 'El tipo de archivo no está permitido. Solo se aceptan .pdf, .doc o .docx.',
    'nuevo_file_analysis_preparation_max_size_file_KO': 'El archivo excede el tamaño permitido. Máximo 2 MB.',
    'nuevo_file_analysis_preparation_min_size_name_KO': 'El nombre del archivo es demasiado corto. Debe tener al menos 7 caracteres.',
    'nuevo_file_analysis_preparation_max_size_name_KO': 'El nombre del archivo es demasiado largo. Debe tener menos de 100 caracteres.',
	
	'true': 'Exito',

	'id_project_min_size_KO': 'Número demasiado corto. Debe tener al menos 1 dígito',
	'id_project_max_size_KO': 'Número demasiado largo. Debe tener menos de 11 dígitos',
	'id_project_format_KO': 'Número no válido. Solo se permiten dígitos',

	'name_project_min_size_KO':'Nombre demasiado corto. Debe tener al menos 15 caracteres.',
	'name_project_max_size_KO':'Nombre demasiado largo. Debe tener menos de 100 caracteres.',
	'name_project_format_KO':'Nombre no válido. Debe estar compuesto únicamente por alfabéticos sin acentos ni ñ ni espacios.',

	'start_date_project_format_KO':'Formato de fecha de inicio incorrecto. Debe ser dd/mm/aaaa.',
	'start_date_project_valid_KO':'Fecha de inicio no válida. Debe ser una fecha válida.',

	'end_date_project_format_KO':'Formato de fecha de fin formato incorrecto. Debe ser dd/mm/aaaa.',
	'end_date_project_valid_KO':'Fecha de fin no válida. Debe ser una fecha válida.',

	'responsable_project_min_size_KO':'Responsable demasiado corto. Debe tener al menos 6 caracteres.',
	'responsable_project_max_size_KO':'Responsable demasiado largo. Debe tener menos de 60 caracteres.',
	'responsable_project_format_KO':'Responsable con formato incorrecto. Debe estar compuesto únicamente por alfabéticos con acentos, ñ y espacios.',

	'organization_project_min_size_KO':'Organización demasiado corto. Debe tener al menos 6 caracteres.',
	'organization_project_max_size_KO':'Organización demasiado largo. Debe tener menos de 100 caracteres.',
	'organization_project_format_KO':'Organización con formato incorrecto. Debe estar compuesto únicamente por alfabéticos con acentos, ñ y espacios.',

	'description_project_min_size_KO':'Descripción demasiado corta. Debe tener al menos 30 caracteres.',
	'description_project_max_size_KO':'Descripción demasiado larga. Debe tener menos de 500 caracteres.',

	'file_project_min_size_name_KO':'Archivo demasiado corto. Debe tener al menos 7 caracteres.',
	'file_project_max_size_name_KO':'Archivo demasiado largo. Debe tener menos de 100 caracteres.',
	'file_project_format_name_file_KO':'Archivo con formato incorrecto. Debe estar compuesto únicamente por alfabéticos con acentos, ñ, espacios y signos de puntuación.',
	'file_project_max_size_file_KO':'Archivo con tamaño incorrecto. Debe tener un tamaño inferior a 2000000 bytes.',
	'file_project_type_file_KO':'Archvio con formato incorrecto. Debe estar compuesto por una extensión .pdf, .doc o .docx.',

	'nuevo_file_project_min_size_name_KO':'Archivo demasiado corto. Debe tener al menos 7 caracteres.',
	'nuevo_file_project_max_size_name_KO':'Archivo demasiado largo. Debe tener menos de 100 caracteres.',
	'nuevo_file_project_format_name_file_KO':'Archivo con formato incorrecto. Debe estar compuesto únicamente por alfabéticos con acentos, ñ, espacios y signos de puntuación.',
	'nuevo_file_project_max_size_file_KO':'Archivo con tamaño incorrecto. Debe tener un tamaño inferior a 2000000 bytes.',
	'nuevo_file_project_type_file_KO':'Archvio con formato incorrecto. Debe estar compuesto por una extensión .pdf, .doc o .docx.',

	'code_project_min_size_KO':'Código demasiado corto. Debe tener al menos 6 caracteres.',
	'code_project_max_size_KO':'Código demasiado largo. Debe tener menos de 50 caracteres.',
	'code_project_format_KO':'Código con formato incorrecto. Debe estar compuesto únicamente por alfabéticos sin acentos ni ñ ni espacios',

	'acronym_project_min_size_KO':'Acrónimo demasiado corto. Debe tener al menos 6 caracteres.',
	'acronym_project_max_size_KO':'Acrónimo demasiado largo. Debe tener menos de 15 caracteres.',
	'acronym_project_format_KO':'Acrónimo con formato incorrecto. debe estar compuesto únicamente por alfabéticos con ñ y signos de puntuación, sin acentos ni espacios.',

	'id_sampling_methodology_min_size_KO':'Número demasiado corto. Debe tener al menos 1 dígito',
	'id_sampling_methodology_max_size_KO':'Número demasiado largo. Debe tener menos de 11 dígitos',
	'id_sampling_methodology_format_KO':'Número no válido. Solo se permiten dígitos',

	//ERRORES BACK
	'id_analysis_preparation_es_nulo_KO': 'Identificación de preparaciones de análisis es nulo. Se esperaba pero no se recibió',
	'name_analysis_preparation_es_nulo_KO': 'Nombre de preparaciones de análisis es nulo. Se esperaba pero no se recibió',
	'description_analysis_preparation_es_nulo_KO': 'Descripción de preparaciones de análisis es nula. Se esperaba pero no se recibió',
	'bib_analysis_preparation_es_nulo_KO': 'Bibliogrfía de preparaciones de análisis es nula. Se esperaba pero no se recibió',
	'file_analysis_preparation_es_nulo_KO': 'No se subió ningún archivo.',
	'id_project_es_nulo_KO': 'Identificación de proyecto es nula. Se esperaba pero no se recibió',
    'name_project_es_nulo_KO': 'Nombre de proyecto es nulo. Se esperaba pero no se recibió',
    'start_date_project_es_nulo_KO': 'Fecha de inicio es nula. Se esperaba pero no se recibió',
    'end_date_project_es_nulo_KO': 'Fecha de fin es nula. Se esperaba pero no se recibió',
    'responsable_project_es_nulo_KO': 'Responsable del proyecto es nulo. Se esperaba pero no se recibió',
    'organization_project_es_nulo_KO': 'Organización del proyecto es nula. Se esperaba pero no se recibió',
    'description_project_es_nulo_KO': 'Descripción de proyecto es nula. Se esperaba pero no se recibió',
    'nuevo_file_project_es_nulo_KO': 'Nuevo archivo de proyecto es nulo. Se esperaba pero no se recibió',
    'file_project_es_nulo_KO': 'Archivo de proyecto es nulo. Se esperaba pero no se recibió',
    'code_project_es_nulo_KO': 'Código es nulo. Se esperaba pero no se recibió',
    'acronym_project_es_nulo_KO': 'Acrónimo es nulo. Se esperaba pero no se recibió',
    'id_sampling_methodology_es_nulo_KO': 'Metodología de muestreo es nula. Se esperaba pero no se recibió',
    'link_file_project_es_nulo_KO': 'Link de archivo de proyecto es nulo. Se esperaba pero no se recibió',
	'SQL_OK': 'Operación realizada correctamente.',
	'SQL_KO': 'La operación falló debido a un error SQL. Algunos datos no están en el formato correcto.',
	'RECORDSET_VACIO': 'La búsqueda no arrojó resultados.',
	'RECORDSET_DATOS': 'La búsqueda devolvió datos.'
}
